tradingstrategy-ai/trade-executor

- tests/test_transaction_builder.py
- tradeexecutor/ethereum/tx.py
- tradeexecutor/state/blockhain_transaction.py
- tradeexecutor/state/trade.py
- Log out planned gas the fees before transaction is broadcasted
- If the transaction broadcast fails, then write more details what is the transaction node rejected
> Better gas price spike reporting

- .github/workflows/client-side.yml
- .github/workflows/tests.yml
- docs/install.md
- docs/testing.md
- poetry.lock
- pyproject.toml
- tests/test_optional_dependencies.py
- tox.ini
Make `trade-executor` installation more manageable under Pyodide.
> Moving web server to optional dependencies

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
- removing protobuf as explicity dependency, web3 still needs this
- re-enable Poetry cache
> Poetry fixes

- tradeexecutor/visual/benchmark.py
Triple the default chart height for benchmark.visualise_benchmark from 800 to 2400.
> triple benchmark default chart height

- tradeexecutor/backtest/backtest_runner.py
As the title says, in backtest_runner.py we now catch import errors from 'tradingstrategy' and 'tradingexecutor' and raise the following import error: 'use "poetry install -E execution" to install dependencies in trade-executor instead of "poetry install"'
> catch import error in backtest_runner

- tests/test_visualisation.py
- tradeexecutor/state/visualisation.py
- We cannot allow `numpy.float64` to slip in the visualisation data, because this number is unserializable
> Fix visulisation type bugs

- tests/test_state.py
- tests/test_unclean_state.py
- tests/test_uniswap_live_stop_loss.py
- tests/test_webhook_api.py
- tradeexecutor/backtest/backtest_execution.py
- tradeexecutor/cli/commands/repair.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/execution.py
- tradeexecutor/ethereum/uniswap_v2_execution.py
- tradeexecutor/ethereum/uniswap_v2_execution_v0.py
- tradeexecutor/state/state.py
- tradeexecutor/state/trade.py
- tradeexecutor/strategy/execution_model.py
- tradeexecutor/strategy/repair.py
- tradeexecutor/strategy/run_state.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/webhook/api.py
- Detect dangling transasctions that were broadcasted but failed to confirm
- Offer `repair` command to fix any dangling transactions
- Refuse to start up with unclean state
> Unclean state handling

- tradeexecutor/ethereum/execution.py
- tradeexecutor/ethereum/uniswap_v2_execution.py
- tradeexecutor/ethereum/web3config.py
- tradeexecutor/testing/simulated_execution_loop.py
- Make sure we have a good `confirmation_block_count` setting when doing live trade execution
> Pass confirmation_block_count around

- tradeexecutor/visual/single_pair.py
Add a new chart type to visualise live trades.
- We use a specific chart to display live positions
- This chart type shows slippage and duration, between the trade start and trade end,
to visualise how much much losses were taken on slippage
- Positions are visualised as area: green is closed for profit, red is closed for loss
- Individual trades, entries and exists are visualised as arrows
- Arrows so the trade duration and slippage move from expected to executed price
> Adding live trading chart

- tests/test_backtest_execution.py
- tests/test_backtest_execution_three_way.py
- tests/test_backtest_inline_synthetic_data.py
- tests/test_backtest_position_trigger.py
- tests/test_position_manager.py
- tests/test_summary_statistics.py
- tradeexecutor/backtest/backtest_pricing.py
- tradeexecutor/ethereum/web3config.py
- Current assumed execution price was the candle close price of the timestamp
- Assume we are so good that we can execute at open price
> Switch backtesting to use open price by default

- tradeexecutor/analysis/trade_analyser.py
Fixes #157. This PR allows calculation of same/similar summary statistics as before, but removes the need for deriving and specifying various parameters to the `calculate_summary_statistics` method. The only remaining optional parameter is the `time_bucket`
> Stats adjust

- .gitignore
- env/local-test.env
- logs/README.md
- tests/test_backtest_execution.py
- tests/test_backtest_inline_synthetic_data.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/log.py
- tradeexecutor/cli/loop.py
- tradeexecutor/strategy/pricing_model.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Add `--file-log-level`
- Make sure that `DEXPair.fee` looks like BPS, not 0...1, as per documentation
- Fix mixture of BPS and 0...1 float fees in multiple places
- Fix portfolio valuation called before strategy receives deposits
> Add log file option and pair fee sanity checks

- tests/strategy_tests/test_defi_bluechip.py
- tradeexecutor/analysis/fee_analyser.py
- tradeexecutor/state/trade.py
- In `tradeexecutor.analysis.fee_analyser` add `analyse_trading_fees`, `create_pair_trading_fee_summary_table`
- List of all trades with their fees
- Trading fee pivot table per trading pair
> Add trade fee analysis

- tests/backtest/test_backtest_inline_synthetic_data.py
- tradeexecutor/analysis/trade_analyser.py
Adds 4 new summary statistics. These stats are relevant to strategies with trailing stop losses where stop losses can occur on winning position, and also strategies where take profits can occur on losing position (if they exist)
1. `winning_stop_losses`
2. `losing_stop_losses`
3. `winning_stop_losses_percent`
4. `losing_stop_losses_percent`
- Fixes #263
> Stop loss more

- tradeexecutor/analysis/grid_search.py
Makes it possible to visualise grid search results where `None` is one of the searched values.
> Correctly draw heatmaps with None and Nan items on axes

- tradeexecutor/state/visualisation.py
- tradeexecutor/visual/technical_indicator.py
- Technical indicators were based on the decision-making timing, not market timing
- This is confusing for the strategy developer
- By default, now show technical indicators matching the timestamps
> Correct look ahead bias fix when plotting technical indicators

- tests/test_state.py
- tradeexecutor/state/state.py
- tradeexecutor/state/validator.py
- Whitelist [numpy.float32 and numpy.float64](https://stackoverflow.com/questions/76430373/converting-pandas-float32-and-float64-to-pythons-native-float-and-loss-of-accu?noredirect=1#comment134769813_76430373) - it's too painful developer experience wise to manually cast these to `float()` all the time
- Add `State.to_json_safe()` to make it easier to test the state serialisation within notebooks
> Friendlier State JSON serialisation

- tradeexecutor/cli/testtrade.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- `close_position()` should always return a list of trades, not None
- Make sure `perform_test_trade` aborts the execution if the first buy fails
> Fix close position signature

- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/strategy/execution_model.py
- tradeexecutor/strategy/sync_model.py
- Run the live trading loop setup before setting the trade executor to web server mode
- Fail at startup if enzyme vault has not been initialised
> Restructuring live trade execution prechecks before the main loop

- strategies/test_only/pandas_buy_every_second_day.py
- tests/backtest/test_backtest_execution.py
- tests/backtest/test_backtest_execution_three_way.py
- tests/backtest/test_backtest_investment_flow.py
- tests/backtest/test_backtest_profit_calculation.py
- tests/ethereum/test_execute_trade_uniswap.py
- tests/ethereum/test_execute_trade_uniswap_v3.py
- tests/mainnet_fork/test_uniswap_v2_routing.py
- tests/mainnet_fork/test_uniswap_v3_routing.py
- tests/test_legacy_state_dump.py
- tests/test_reserves.py
- tests/test_summary_and_metrics.py
- tradeexecutor/backtest/backtest_pricing.py
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/backtest/backtest_sync.py
- tradeexecutor/backtest/legacy_backtest_sync.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/ethereum/hot_wallet_sync_model.py
- tradeexecutor/ethereum/wallet.py
- tradeexecutor/state/balance_update.py
- tradeexecutor/state/position.py
- tradeexecutor/state/statistics.py
- tradeexecutor/state/sync.py
- tradeexecutor/statistics/summary.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/strategy/sync_model.py
- tradeexecutor/testing/dummy_wallet.py
- tradeexecutor/visual/equity_curve.py
- Add different options to calculate profit, funds flow, equity
- Record deposit and redemption USD values for funding calculations
- Export the web frontend summary card profitability [as the compounding realised trading profitability](https://tradingstrategy.ai/docs/programming/market-data/profitability.html), instead of total equity increase to smooth out equity changes caused by deposits and redemptions
> Profit calculation with inflow

- .github/workflows/test-and-build-image.yml
- .github/workflows/test-slow.yml
- pyproject.toml
- strategies/test_only/backtest-cli-command.py
- tests/backtest/test_backtest_open_position.py
- tests/backtest/test_backtest_report.py
- tests/cli/test_cli_commands.py
- tests/strategy_tests/test_pancake_momentum_v2.py
- tests/test_data_age.py
- tests/test_decision_trigger.py
- tests/test_summary_and_metrics.py
- tests/test_webhook_api.py
- tradeexecutor/backtest/backtest_report_template.ipynb
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/backtest/report.py
- tradeexecutor/cli/bootstrap.py
- tradeexecutor/cli/commands/backtest.py
- tradeexecutor/cli/commands/shared_options.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/cli/main.py
- tradeexecutor/state/metadata.py
- tradeexecutor/state/state.py
- tradeexecutor/strategy/run_state.py
- tradeexecutor/strategy/strategy_module.py
- tradeexecutor/strategy/summary.py
- tradeexecutor/strategy/trading_strategy_universe.py
- tradeexecutor/webhook/api.py
- Move `backtest` to a separate CLI command from `start`
- Change strategy module structure to `0.2` that contains the default backtest parameters in the strategy module itself
- `backtest` generates a backtested state file
- `backtest` generates a static HTML file to be displayed in the web frontend for the backtest results
- Because we exceeded 20 minutes run-time for Github Actions, split slow tests to their own `slow_test_group` pytest marker and run these tests in a separate Github Actions workflow
> Backtest CLI command

- tradeexecutor/cli/loop.py
- `refresh_run_live_state()` should be always run at `trade-executor` start, as otherwise strategy summary tile lacks data
> Always do summary statistics

- tradeexecutor/cli/bootstrap.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/state/metadata.py
- tradeexecutor/statistics/summary.py
- Make sure key metrics is always called
- Make key metrics backtest vs. live trading cut off period configurable
> Empty summary statistics fix #2

- tests/test_strategy_state_visualisation_multipair.py
- tests/test_webhook_api.py
- tradeexecutor/state/visualisation.py
- tradeexecutor/strategy/pandas_trader/runner.py
- tradeexecutor/strategy/run_state.py
- tradeexecutor/visual/strategy_state.py
- Allows reporting of multipair charts in Discord for strategies with up to 3 pairs
- Fixes bugs in the image generation for the frontend 
- Combines multiple small images into one using subplots, instead of providing list of figures
> Multipair discord reporting

- poetry.lock
- tests/backtest/test_backtest_profit_calculation.py
- tests/test_equity_curve.py
- tests/test_summary_and_metrics.py
- tradeexecutor/state/state.py
- tradeexecutor/statistics/summary.py
- tradeexecutor/visual/equity_curve.py
By default, always insert a bookkeeping market at thefirst and  last available date, so web frontend can deal with the data easier.
- Add `State.get_strategy_time_range`
- Add `calculate_compounding_realised_trading_profitability(fill_current_time_gap)`
> Add end timestamp marked to the profitability chart data

- strategies/ema-crossover-long-only-no-stop-loss.py
- tests/backtest/test_backtest_ema_crossover.py
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/cli/loop.py
- tradeexecutor/state/state.py
- tradeexecutor/strategy/cycle.py
- tradeexecutor/visual/multiple_pairs.py
- tradeexecutor/visual/single_pair.py
- Adds `minimum_data_lookback_range` that can be used instead of `start_at` and `end_at` for backtesting
- Automatically uses entire data range for token if not dates specified
- Allows visualisations to automatically pick start and end for the full strategy time range after the strategy is run
- fixes #370
> Auto backtest range

- poetry.lock
- tests/enzyme/test_enzyme_correct_accounting.py
- tradeexecutor/strategy/account_correction.py
- Do both absolute token unit and relative checks when checking for accounting rounding errors and dust
> Fixing to use relative values when checking account dust

- tests/ethereum/test_uniswap_v3_live_stop_loss.py
- tradeexecutor/strategy/pandas_trader/runner.py
- tradeexecutor/visual/image_output.py
- tradeexecutor/webhook/api.py
- switch `Content-Type` header to `image/svg+xml`
- adds format parameter to `open_bytes_in_browser` so that both svg and png show up in testing
> switch to svg

- tests/interest/test_state_short.py
- tradeexecutor/state/balance_update.py
- tradeexecutor/state/loan.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/interest.py
- We need to pass the US dollar price of `vToken` for some calculations to be correct
- Add `update_leveraged_position_interest` that updates both atoken and vtoken intersst amount in one go
- Add `estimate_interest` that allows to generate new atoken amount in unit tests
- Include unrealised short PnL test with interest calculations
> Short position interest tests

- tests/interest/test_state_short.py
- tests/mainnet_fork/test_frozen_position_and_blacklist.py
- tests/test_state.py
- tradeexecutor/backtest/backtest_sync.py
- tradeexecutor/backtest/backtest_valuation.py
- tradeexecutor/cli/loop.py
- tradeexecutor/state/portfolio.py
- tradeexecutor/state/position.py
- tradeexecutor/state/state.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/strategy/sync_model.py
- tradeexecutor/strategy/valuation.py
- Allow sync_interests() to re-value loans as well, to make sure we have updated price available as it is needed for several loan calculations
- Re-work `ValuationModel` and move logic out from state classes to avoid circular imports
- Fix some tests that for some reason now produce US dollar values a bit off from the original
> Valuation changes

- tests/backtest/test_backtest_short_synthetic_data.py
- tests/interest/test_state_short.py
- tradeexecutor/backtest/backtest_execution.py
- tradeexecutor/backtest/backtest_sync.py
- tradeexecutor/backtest/simulated_wallet.py
- tradeexecutor/state/identifier.py
- tradeexecutor/state/interest.py
- tradeexecutor/state/position.py
- tradeexecutor/state/state.py
- tradeexecutor/state/statistics.py
- tradeexecutor/state/trade.py
- tradeexecutor/statistics/core.py
- tradeexecutor/strategy/interest.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- Update `SimulatedWallet` to correctly handle aToken and vToken 
- Make sure we correctly account for collateral leveraged quantity when opening a short position
- Make sure we correctly unwind the collateral when closing a short position
- Fix the issue where `TradeExecution.claimed_interest` was not credited back to portfolio cash reserves
TODO: There is still a future work. Currently `paid_interest` and `claimed_interest` do not have separate (planned, executed) life cycle as other `TradeExecution` variables. The live trading system will break when `paid_interest` will be different from the planned value, because aToken/vToken dynamic balance changes and the time lag before planning the trade and getting it executed.
> Short position close fixes

- tradeexecutor/strategy/runner.py
- Verify on-chain account balances after the post-trade step is complete
- This should give early alert for malfunctioning tokens received in the wallet
> More checks on accounts

- tradeexecutor/strategy/pandas_trader/position_manager.py
Part of #579
Add new methods:
- `is_any_long_position_open()`
- `is_any_short_position_open()`
- `is_any_credit_supply_position_open()`
- `get_current_long_position()`
- `get_current_short_position()`
- `get_current_credit_supply_position()`
So in `decide_trade()` cycle we can easily identify and pick the correct position to entry and exit
> Filtering positions by kind

- tradeexecutor/visual/multiple_pairs.py
fixes #521
Note: volume shows on top of candlesticks. However, this shouldn't be a major issue, since volume is disabled by default for multipair visualisations anyway (due to clutter)
> fix visualise_multipair volume

- tradeexecutor/state/position.py
- tradeexecutor/strategy/alpha_model.py
- tradeexecutor/strategy/bootstrap.py
- tradeexecutor/strategy/output.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/runner.py
- `check_accounts` was not run as a part of main loop even it was supposed to be
- Add more logging regarding position sizes to track down problems with `polygon-momentum-multipair` portfolio construction strategy - suspected increasing position size caused the accounting mismatch
> Accounting balance checks were not correctly run in live execution

- tests/ethereum/test_uniswap_live_stop_loss.py
- tradeexecutor/ethereum/enzyme/tx.py
- tradeexecutor/ethereum/routing_model.py
- tradeexecutor/ethereum/routing_state.py
- tradeexecutor/ethereum/tx.py
- tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py
- tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py
- tradeexecutor/state/blockhain_transaction.py
- tradeexecutor/strategy/account_correction.py
- tradeexecutor/strategy/output.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- Add `BlockchainTransaction.notes` text field
- Fill this field with text information about the trade controlling the transaction
- Have this information in the log output
-> Allows us to diagnose what goes wrong with the transactions.
> Add human-readable diagnostics notes to blockchain transactions

- .github/workflows/test-and-build-image.yml
- Use Github cache action to avoid redownloading datasets between test runs
- This flow is already enabled by default in local testing (`/tmp/trading-strategy-tests/ ` stays intact)
> Cache datsets

- tradeexecutor/state/position.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/visual/utils.py
- Currently the treasury was not synced before stop loss trigger
- If there was a deposit before a trigger executed a trade it would fail
> Sync treasury before stop position trigger check

- poetry.lock
- pyproject.toml
- tradeexecutor/backtest/backtest_sync.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/ethereum/hot_wallet_sync_model.py
- tradeexecutor/ethereum/wallet.py
- tradeexecutor/strategy/account_correction.py
- tradeexecutor/strategy/sync_model.py
- tradeexecutor/utils/blockchain.py
- Make sure we update treasury last block scanned correctly when directly reading correction balances on-chain
> Adding block identifier logic to account correction

- tradeexecutor/cli/loop.py
- tradeexecutor/state/balance_update.py
- tradeexecutor/statistics/core.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/visual/equity_curve.py
- Current deposit/redemption was reflected in the state, but not in the statistics
- Frontend displayed a wrong TVL amount for a while until there was a refresh
- Log deposits and redemptions to Discord
- Tune `check_accounts()` logging level according to the situation
> Revalue portfolio right after we see deposits

- tests/enzyme/test_enzyme_correct_accounting.py
- tradeexecutor/backtest/backtest_execution.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/execution.py
- tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution_v0.py
- tradeexecutor/state/position.py
- tradeexecutor/state/trade.py
- tradeexecutor/strategy/account_correction.py
- tradeexecutor/strategy/dummy.py
- tradeexecutor/strategy/execution_model.py
- tradeexecutor/strategy/runner.py
- Figure out why there are still some mismatch on-chain amounts vs. expected
- Warn about frozen positions in `check-accounts` and `correct-accounts`
- Don't allow `correct-accounts` before `repair` has been run
> Working on post-trade execution bugs

- tests/enzyme/test_enzyme_correct_accounting.py
- tests/enzyme/test_enzyme_trade.py
- tradeexecutor/ethereum/enzyme/tx.py
- tradeexecutor/ethereum/routing_model.py
- tradeexecutor/ethereum/routing_state.py
- tradeexecutor/ethereum/tx.py
- tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py
- tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py
- tradeexecutor/state/trade.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- Fix the slippage tolerance conversion when calling Uniswap v3 trades, must be BPS, not %
> Slippage tolerance conversion fix and sanity checks

- tradeexecutor/backtest/backtest_execution.py
- tradeexecutor/backtest/backtest_sync.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/ethereum/execution.py
- tradeexecutor/ethereum/hot_wallet_sync_model.py
- tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution_v0.py
- tradeexecutor/state/types.py
- tradeexecutor/strategy/dummy.py
- tradeexecutor/strategy/execution_model.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/strategy/sync_model.py
- Make execution more deterministic by enforcing certain `end_block` parameter until which we take account deposits/redemptions and relevant balance checks
- Note that the current method is not safe until we have atomic rebalances; it is impractical for high number of trades
> Safe end block number

- tradeexecutor/state/portfolio.py
- tradeexecutor/visual/utils.py
- Makes winning stop losses a different colour from losing stop losses in the visualisations
- Fixes #624
> Make winning stop loss a different colour

- notebooks/live-strategy-analysis/analyse-balance-events.ipynb
- notebooks/live-strategy-analysis/analyse-eth-usdc.ipynb
- tests/enzyme/conftest.py
- tests/enzyme/test_enzyme_realised_profit.py
- tests/enzyme/test_enzyme_redeem.py
- tests/strategy_tests/test_long_short_momentum.py
- tradeexecutor/state/identifier.py
- tradeexecutor/state/position.py
- tradeexecutor/state/state.py
- Fix realised PnL calculation in the case spot positions contain in-kind redemptions
- Allow mixing `str` and `Path` in state serialisation
- Change `hash()` for `TradingPairIdentifier`  to be independent from the internal id. Hash together (base, quote, fee) like Uniswap v3 does.
> Adding in-kind redemptions fix for realised PnL

- tests/interest/test_missing_lending_data.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/strategy/pandas_trader/runner.py
- Fix hang in Plot's Kaleido chart rendering backend
- Enable Python's `faulthandler` so we should able to use external UNIX signals to get a Python thread dump from inside Docker
Attempt to fix https://github.com/tradingstrategy-ai/trade-executor/issues/699
> Workaround for Kaleido crash issues

- tests/ethereum/polygon_forked/generic-router/test_generic_router.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py
- tradeexecutor/ethereum/one_delta/one_delta_routing.py
- Enable `test_generic_routing_check_accounts`
Currently failing bit still thinks there is a minor tweak needed for aUSDC:
```
assert asset_to_position_mapping[asset_usdc].quantity == Decimal("9600")
assert asset_to_position_mapping[asset_wmatic].quantity == pytest.approx(Decimal(174.375401861648687986))
assert asset_to_position_mapping[weth_usdc_shorting_pair.base].quantity == pytest.approx(Decimal(0.3678414988406300651822788816))
assert asset_to_position_mapping[weth_usdc_shorting_pair.quote].quantity == pytest.approx(Decimal(898.1999999999999999625299729))
assert len(asset_to_position_mapping) == 4
corrections = calculate_account_corrections(
pair_universe=strategy_universe.data_universe.pairs,
reserve_assets=state.portfolio.get_reserve_assets(),
state=state,
sync_model=sync_model, …
```
> Enable aUSDC check in the tests

- strategies/test_only/generic_routing_end_to_end_spot.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py
- tradeexecutor/cli/commands/perform_test_trade.py
- tradeexecutor/state/identifier.py
- tradeexecutor/strategy/lending_protocol_leverage.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Add `test_generic_routing_live_trading_start_spot_only` and `test_generic_routing_test_trade_spot_only`
- Fix `AssetType` not being enum, causing serialisation failures
- Fix problems with passing exchanges to `Universe` construction
> Generic routing spot only e2e

- tests/enzyme/test_enzyme_deposit.py
- tests/enzyme/test_enzyme_end_to_end.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/cli/commands/reset_deposits.py
- tradeexecutor/ethereum/execution.py
- tradeexecutor/strategy/account_correction.py
- `correct-accounts` command line command did not handle a case where there were unaccounted tokens on an already closed position
- Move those tokens to clean up account
> Correct accounts on closed position

- tests/cli/test_cli_correct_account_price_missing.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/asset.py
- `calculate_quantity_usd_value()` did not function correctly for a position without any good price data, prevented running `correct_accounts`
- When running `correct_accounts` associate any token without a position to the last closed position, not the first one
> Fix calculate_quantity_usd_value

- tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py
- tradeexecutor/cli/commands/perform_test_trade.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/cli/testtrade.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/execution_context.py
- tradeexecutor/strategy/interest.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/trading_strategy_universe.py
- tradeexecutor/utils/accuracy.py
- End-to-end start spot and short strategy run test with 10 cycles
- End-to-end perform test trade test: open and close short for pairs that do support shorting
- Uses forked Polygon mainnet
> Generic routing spot and short tests

- tradeexecutor/analysis/trade_analyser.py
- tradeexecutor/statistics/key_metric.py
- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/statistics/summary.py
- tradeexecutor/strategy/summary.py
- Adds support for separate key metrics for longing and shorting in `calculate_summary_statistics`
- This is so that these statistics can be displayed on the TradingStrategy frontend
- Adds support for a new class `StatisticsTable`, that can be used to store any table data where the data points can be represented as `KeyMetrics`
- Fixes #706 
CC @kenkunz
> Long short metrics

- strategies/spot-and-short-momentum-4.py
- strategies/spot-and-short-momentum-grid-3.py
- strategies/spot-and-short-momentum-grid.py
- strategies/spot-and-short-momentum-tuned.py
- strategies/spot-and-short-momentum.py
- strategies/test_only/generic_routing_end_to_end.py
- strategies/test_only/polygon-eth-spot-short-bb.py
- tests/backtest/test_backtest_credit_supply_mock.py
- tests/backtest/test_backtest_credit_supply_real_data.py
- tests/backtest/test_backtest_short_real_data.py
- tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py
- tests/ethereum/polygon_forked/generic-router/conftest.py
- tests/ethereum/polygon_forked/generic-router/test_short_flags.py
- tests/ethereum/test_aave_v3_interest.py
- tests/interest/test_lending_dataset.py
- tests/interest/test_missing_lending_data.py
- tradeexecutor/ethereum/aave_v3/interests.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Polygon renamed USDC -> USDC.e
- Native USDC is now USDC on Polygon
- This breaks a lot of assumptions regarding USDC stablecoin as we have now two of them
- This PR will make tests and strategies to address tokens by the USDC address instead of just symbol USDC
> Usdc.e fixes

- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/strategy/summary.py
- Fix the new summary metrics table in RunState causing excessive serialisation and then crash by hanging
> Fix long short table serialisation

- tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py
- tests/test_state.py
- tradeexecutor/cli/commands/perform_test_trade.py
- tradeexecutor/cli/loop.py
- tradeexecutor/cli/testtrade.py
- tradeexecutor/statistics/core.py
- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/visual/equity_curve.py
- Currently, long short metrics doesn't use backtested state. This PR aims to fix that
- fixes #757
- Adds a new argument to `update_statistics`, `long_short_metrics_latest`. This needs is always provided during live trading
> add backtested state to long short metrics

- tests/backtest/test_backtest_profit_calculation.py
- tradeexecutor/statistics/key_metric.py
- Some stats were incorrect (see #747 and #749) due to resampling. The resampling caused data points to be lost.
- PR #748 already fixed the profit calculation by not using resampled data. However, there were other stats such as Sortino, Sharpe, etc. that used the incorrect resampled data
- This PR fixes the root cause of the issue by correcting the resampling not to lose any data points
- fixes #747
- fixes #749
> Fix all key metrics

- tests/backtest/test_backtest_mixed_positions.py
- tradeexecutor/analysis/trade_analyser.py
- tradeexecutor/visual/equity_curve.py
- Adds `calculate_long_compounding_realised_trading_profitability` and `calculate_short_compounding_realised_trading_profitability`. 
- This required the internal workings of `calculate_compounding_realised_trading_profitability` and `calculate_size_relative_realised_trading_returns` to be modified. Namely, they now call private methods that accept a list of `positions` as an argument. So now we can provide all positions, only long or only short postions
- This small PR is part of fixing larger issue #726
> Calculate compounding returns for long and short

- tests/backtest/test_backtest_mixed_positions.py
- tests/backtest/test_backtest_short_synthetic_data.py
- tests/enzyme/test_enzyme_realised_profit.py
- tests/test_summary_and_metrics.py
- tradeexecutor/state/position.py
- Unblocks #726
- This PR goes some way to fixing #761 
- With this PR, the shorting profit percentage calculations are correct down to 3 decimal places. This means that they are still not totally correct but much more accurate than before
Here is an `equity curve` plotted against `compounding position returns` before and after:
Clearly much better now.
> fix shorting profit percent calculations

- tests/backtest/test_backtest_profit_calculation.py
- tradeexecutor/visual/equity_curve.py
- This PR fixes and tests a test for `calculate_cumulative_daily_returns`
- Fixes #805
Before After:
> Fix performance chart 90 days

- tests/backtest/test_backtest_profit_calculation.py
- tests/test_state.py
- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/visual/equity_curve.py
> Fix annualised return percent

- tests/backtest/test_backtest_inline_synthetic_data.py
- tests/backtest/test_backtest_open_position.py
- tradeexecutor/analysis/trade_analyser.py
- tradeexecutor/state/state.py
- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/statistics/summary.py
- fixes #787
- Changes `trading period length` to be the entire duration of the backtest/live strategy, not `last.executed_at - first.executed_at`
> align strategy duration

- tradeexecutor/backtest/grid_search.py
- tradeexecutor/cli/loop.py
- Datalore cannot render grid search progress bar properly
- Explicitly do not display a backtest progress bar when run in a grid search mode (note that these were displayed correctly in a normal Jupyter environment when using a threaded grid search, but now are completely gone)
- Make Binance download to save temp datasets under `~/.cache`
> Hide individual progress bars in a backtest

- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/backtest/grid_search.py
- `BacktestSetup.grid_search` was not correctly being set
> Pass grid search parameter correctly around

- tests/backtest/test_backtest_inline_synthetic_data.py
- tradeexecutor/analysis/trade_analyser.py
- tradeexecutor/statistics/statistics_table.py
- tradeexecutor/strategy/summary.py
- renames `average_duration_between_positions` to `average_duration_between_position_openings`
- adds average_interest_paid_usd, median_interest_paid_usd, max_interest_paid_usd, min_interest_paid_usd, total_interest_paid_usd, average_duration_between_position_openings, average_position_frequency to frontend stats
> add more stats to frontend

- tests/ethereum/polygon_forked/conftest.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_multihops.py
- tests/test_routing_data.py
- tradeexecutor/ethereum/routing_data.py
- Add WETH to be allowed intermediate token in Quickswap routing
- Add mainnet fork test to make sure 3-way trade works
Fix #849
> Quickswap multihops routing

- tests/backtest/test_forward_fill.py
- tradeexecutor/strategy/pandas_trader/runner.py
- Forward-filled universe loses "timestamp" column on the candle data
- ETH-BTC-USDC strat needs this column
> Missing timestamp column

- tests/web/test_webhook_api.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/state/store.py
- tradeexecutor/strategy/run_state.py
- tradeexecutor/webhook/api.py
- `web_chart` endpoint is too slow if it needs to deserialise JSON state from the disk to draw charts
- Fixes production trade-executor overview chart loading too slowly
- Keep in-memory copy of the state produces with `copy.deepcopy`
> Add in-memory state copy for web API endpoints

- tests/test_summary_and_metrics.py
- tradeexecutor/state/metadata.py
- tradeexecutor/statistics/key_metric.py
- tradeexecutor/strategy/summary.py
- Export CAGR metric as the key metrics to the frontend
- Set the live/backtest switch cut off date 90 days -> 2 years
- 90 days is not statistically meaningful time frame for any of the current strategies
> Add CAGR, make the default backtest cut off to 2 years

- strategies/eth-btc-usdc.py
- tradeexecutor/cli/result.py
- tradeexecutor/statistics/key_metric.py
- Currently there was disparities between the two different calculation method for CAGR and Sharpe
- Performance sheet using QuantStats with daily returns
- Key metrics using a different method with net flow adjusted profit
- Likely because of having sparse vs. non-sparse data and different index lengths and this breaks something in QuantStats
- Do a stop gap fix to use always the same form of CAGR and Sharpe calculation for backtested key metric results
> Fix backtest key metrics calculations to be the same as quantstats

- tests/backtest/test_backtest_result_visualisation.py
- tests/strategy_tests/test_defi_bluechip.py
- tests/test_strategy_state_visualisation.py
- tests/test_strategy_state_visualisation_multipair.py
- tradeexecutor/cli/discord.py
- tradeexecutor/statistics/in_memory_statistics.py
- tradeexecutor/strategy/pandas_trader/runner.py
- tradeexecutor/visual/multiple_pairs.py
- tradeexecutor/visual/single_pair.py
- tradeexecutor/visual/strategy_state.py
- tradeexecutor/visual/utils.py
- Having old visualisation data in the state file causes asserts to trigger
- We do not want this in the live trading, instead we want to ignore and continue gracefully
- Pass `ExecutionContext` all the way down to the visualisation code so that this does not cause live execution to crash (backtest still should crash with an assert exception)
> Fix live visualisation crashing if the visualisation labels are changed

- tests/test_strategy_state_visualisation_multipair.py
- tradeexecutor/cli/commands/visualise.py
- tradeexecutor/state/visualisation.py
- tradeexecutor/visual/strategy_state.py
- Add support for `state.visualisation.set_visualised_pairs()` to override default trading pairs which are used for price chart
- Save pair IDs in `state.visualisation.pair_ids`
> Support set visualised pairs in strategy

- tests/enzyme/test_enzyme_realised_profit.py
- tests/test_state.py
- tradeexecutor/state/position.py
- tradeexecutor/testing/unit_test_trader.py
- Add `get_unrealised_and_realised_profit_percent` that should give you what the final realised profit is if the position would be immediately closed
- In-kind redemptions make this very complex
- Fixes to unrealised and realised PnL calculations with in-kind redemptions reducing the position
> Create sensible unrealised PnL for positions

- notebooks/breakout-bollinger-bands-new/matic/v02-matic-breakout-single.ipynb
- notebooks/breakout-bollinger-bands-new/matic/v03-matic-breakout-regime-filter.ipynb
- strategies/matic-breakout.py
- strategies/matic-eth-usdc.py
- tests/units_tests/test_strategy_module.py
- tradeexecutor/cli/bootstrap.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/state/metadata.py
- tradeexecutor/strategy/strategy_module.py
- tradeexecutor/strategy/tag.py
- Add new strategy module and metadata attribute `sort_priority` that allows to manually adjust the display order of the strategies in the frontend
- Higher `sort_priority` means strategy comes earlier in the sort order
- Default value is zero
- Deprecated, old, strategies can be moved to the button
> Adding strategy sort priority as the part of the UI

- strategies/matic-breakout.py
- tests/backtest/test_indicator.py
- tradeexecutor/strategy/pandas_trader/indicator.py
- tradeexecutor/strategy/pandas_trader/strategy_input.py
- We had technical indicators where the `pd.Series.index` was not `pd.DateTimeIndex`
- Always force index to be flat `pd.DateTimeIndex` when indicators are calculated
> Fix live data and indicator index issues

- tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py
- tradeexecutor/cli/loop.py
- tradeexecutor/ethereum/one_delta/one_delta_valuation.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/interest.py
- Fix `OneDeltaPoolRevaluator` so it can use latest price from pricing model instead of relying from price from `sync_interests()` cycle
- Add `revalue_base_asset()` logic to `OneDeltaPoolRevaluator`, so legacy `last_token_price` is updated at the same time
Fix #905
> Fix short position valuation

- tradeexecutor/utils/crossover.py
Allowing float/int, as was previously done, in `contains_cross_over` or `contains_cross_under` can lead to many missed crossovers/unders
> don't allow float/int in crossover check

- tradeexecutor/analysis/multi_asset_benchmark.py
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/visual/grid_search.py
- Adjusts backtest to use `backtest_start` and `backtest_end` from `StrategyParameters` if provided
- Trims grid search benchmark start date to match equity curve
> Template notebooks

- tests/test_state.py
- tests/test_strategy_state_visualisation_multipair.py
- tradeexecutor/state/position.py
- tradeexecutor/visual/multiple_pairs.py
- tradeexecutor/visual/single_pair.py
- tradeexecutor/visual/strategy_state.py
- tradeexecutor/visual/technical_indicator.py
- tradeexecutor/visual/utils.py
- Fixes #966 and fixes #457
- Only raises an error message when user  tries to use `visualise_single_pair` in multipair universe without providing `pair` argument in `decide_trades`, this should be far less breaking, if at all, than always raising. 
- Some small refactoring for visual util functions
- The legend still shows for all pairs, have opened ticket #968 for this
> Indicator fix 

- tradeexecutor/backtest/grid_search.py
- tradeexecutor/backtest/optimiser.py
- Joblib should be faster than stdlib pickle for numpy arrays
- Make it possible to save state as the part of the grid search results, now only enabled for the optimiser
> Switch to joblib based pickle for GridSearchResult

- tradeexecutor/backtest/optimiser.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/execution_context.py
- tradeexecutor/utils/list.py
- tradeexecutor/utils/notebook.py
- tradeexecutor/utils/profile.py
- tradeexecutor/visual/single_pair.py
- tradeexecutor/visual/technical_indicator.py
- Add `perform_optimisation(draw_visualisation=False)`
- By default visualisations are disabled in the optimiser, as they slow down the optimisation process
- Add `visualise_single_position()` to diagnose lost trades
- Optimise `export_plot_as_dataframe`
- Use optimised path for `pd.to_datetime`
- Force UTC timezone during the conversation as it gives better performance: **might cause timezone breakage and out of sync issues if some other charting functions did not force UTC before**    
- Much further speedups possible by passing UNIX timestamp in raw to Plotly instead of converting it forth and back to pd.DateTime
- Add some profiling and list utils
> Visualise single position

- tests/backtest/test_grid_search.py
- tradeexecutor/analysis/advanced_metrics.py
- tradeexecutor/backtest/grid_search.py
- tradeexecutor/backtest/optimiser.py
- Allow to set `perform_optimisation(ignore_wallet_errors=True)` which allow the optimiser run to complete, even though some backtests are crashing
> Ignore grid search failures

- tradeexecutor/backtest/optimiser.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Should harden against bugs and yield some speed
- Fix issue with optimizer exception handler not setting the filtered value correctly
> Turn TradingStrategyUniverse to a slotted class

- poetry.lock
- pyproject.toml
- tradeexecutor/backtest/grid_search.py
- tradeexecutor/cli/loop.py
- Use zstd to compress the full state file
- Optimiser search results may take up to 200 GB
> Have compressed state for grid search results

- tests/test_rebalance.py
- tradeexecutor/strategy/alpha_model.py
- When having too few signals/assets to work with, cap the allocation for a single asset
> Add cap to normalise_weight()

- tests/web/test_webhook_api.py
- tradeexecutor/cli/commands/webapi.py
- tradeexecutor/cli/main.py
- tradeexecutor/strategy/run_state.py
- Create a command to run web server directly without execution loop
- Improve `/status` endpoint: `to_dict()` is very slow when state file is big, so we have to remove `read_only_state_copy` before that
> Improve web status endpoint

- strategies/eth-btc-usdc-credit.py
- tests/mainnet_fork/test_enzyme_guard_credit_positions.py
- tests/strategy_tests/test_eth_btc_momentum_credit.py
- tradeexecutor/backtest/backtest_report_template.ipynb
- tradeexecutor/backtest/tearsheet.py
- tradeexecutor/cli/commands/backtest.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/cli/result.py
- tradeexecutor/strategy/alpha_model.py
- Add credit supply support for one of the existing strategies
- Wrap backtest report template blocks that can fail with exception with a graceful handler
To debug report exceptions:
```shell
pytest -k test_eth_btc_momentum_credit 
```
> Update ETH/BTC momentum to use credit positions

- tests/enzyme/conftest.py
- tests/enzyme/test_enzyme_end_to_end.py
- tests/mainnet_fork/test_enzyme_guard_credit_positions.py
- tradeexecutor/cli/commands/deploy_guard.py
- tradeexecutor/cli/commands/enzyme_deploy_vault.py
- tradeexecutor/cli/commands/shared_options.py
- tradeexecutor/cli/guard.py
- tradeexecutor/cli/main.py
- tradeexecutor/strategy/interest.py
- Add a separate `deploy-guard` CLI command
- Currently this command is a bit useless, as the migration path for the guard goes through Enzyme vault `createReconfigurationRequest` function and 7 days delay that is not yet supported
> Deploy guard

- tradeexecutor/cli/close_all.py
- Add extra checks to CLI `close-all` command as if there are accounting issues, the closed position amounts will be incorrect
> Add sanity check to double check availble trading vs. quantity

- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/strategy/account_correction.py
- Running correct-accounts if you have unexecuted trades will result to invalid balances
- Allow correct-accounts to handle opening a new spot for a token that has multiple pairs
> Don't allow to run correct-accounts if unexecuted tradeS

- strategies/test_only/enzyme-polygon-eth-breakout.py
- tests/mainnet_fork/test_correct_credit_position_redemption.py
- tradeexecutor/state/identifier.py
- tradeexecutor/state/interest.py
- tradeexecutor/strategy/account_correction.py
- tradeexecutor/strategy/interest.py
- tradeexecutor/strategy/lending_protocol_leverage.py
- When performing `correct-accounts`, reset any tracked interest rate data for aUSDC positions as we have lost the tracking of interest rates in these manual repair cases
> Add a way to reset the loan position needed for correct accounts

- tests/backtest/test_backtest_inline_real_data.py
- tests/test_strategy_state_visualisation.py
- tradeexecutor/analysis/curve.py
- tradeexecutor/state/visualisation.py
- tradeexecutor/strategy/alpha_model.py
- tradeexecutor/strategy/weighting.py
- Add `visualisation.get_series()` so you can easily chart custom indicators in notebooks
- Add new weighting method `weight_by_1_slash_signal` for volatility weighting
- Add some new default colours for benchmark assets
> Add visualisation.get_series(), new weighting

- pyproject.toml
- tests/backtest/test_backtest_credit_supply_mock.py
- tests/backtest/test_backtest_credit_supply_real_data.py
- tests/backtest/test_backtest_short_real_data.py
- tests/backtest/test_decide_trades_v3.py
- tests/backtest/test_grid_search.py
- tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py
- tests/interest/test_lending_dataset.py
- tradeexecutor/strategy/trading_strategy_universe.py
Currently lending candles are loaded with same time bucket as the main trading data bucket.
Since the purpose of lending candles is totally different, mainly for calculating interest rate, we should get it as realtime as posisble
Fix #1037
> Force loading lending candles time bucket to be 1h

- strategies/eth-btc-usdc-size-risk.py
- strategies/test_only/price_impact_crash.py
- tests/cli/test_cli_commands.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router.py
- tests/ethereum/polygon_forked/generic-router/test_short_flags.py
- tests/mainnet_fork/test_price_impact_crash.py
- tests/strategy_tests/test_eth_btc_trade_size.py
- tests/web/test_webhook_main_loop_crash.py
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/cli/bootstrap.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/loop.py
- tradeexecutor/state/trade.py
- tradeexecutor/strategy/bootstrap.py
- tradeexecutor/strategy/factory.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/parameters.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/strategy/strategy_module.py
- tradeexecutor/strategy/trade_pricing.py
- Add explicit maximum price impact tolerance tripwire
- Crash trade-executor if we detect a trade with more impact attempts to be executed
- Add `Parameters.max_price_impact` so a strategy can have rough control on what kind of trades are allowed
- Use `SizeRiskModel` in `decide_trades()` to resize trades to that `max_price_impact` will be never reached
> Maximum price impact

- tests/backtest/test_backtest_inline_synthetic_data.py
- tests/test_state.py
- tradeexecutor/analysis/trade_analyser.py
- tradeexecutor/backtest/backtest_module.py
- tradeexecutor/backtest/backtest_pricing.py
- tradeexecutor/cli/log.py
- tradeexecutor/cli/result.py
- tradeexecutor/statistics/key_metric.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/utils/summarydataframe.py
- tradeexecutor/visual/equity_curve.py
- `backtest` command was using a wrong trading period to calculate metrics
> Fix backtest trading period

- tests/backtest/test_grid_search.py
- tests/units_tests/test_market_limit.py
- tradeexecutor/cli/loop.py
- tradeexecutor/state/position.py
- tradeexecutor/statistics/core.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
Continue #1047 to fix remaining problems in #1046
- Fix partial tp setup in market limit order
- Fix visualization bug of equity curve
- Fix recording partial tp trigger at wrong price
> Fix partial tp and visualization

- strategies/eth-btc-usdc-size-risk.py
- strategies/test_only/enzyme-polygon-eth-btc-rsi.py
- tests/mainnet_fork/test_enzyme_redeem_dust.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/strategy/account_correction.py
- `enzyme-polygon-eth-btc-rsi` executor was crashing, because Enzyme was redeeming 1 raw unit of aPolUSDC on a dusty closed position
- Have a dust filter on any incoming Enzyme redemption event data
> Enzyme redeem dust fix

- strategies/test_only/enzyme_end_to_end_multipair.py
- tests/backtest/test_custom_labels.py
- tests/backtest/test_other_data.py
- tradeexecutor/backtest/data_preload.py
- tradeexecutor/cli/commands/perform_test_trade.py
- tradeexecutor/cli/commands/webapi.py
- tradeexecutor/state/identifier.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Add `other_data` structure to assets and trading pairs
- Add a standard way of tagging assets with `AssetIdentifier.set_tags`
- Update tests to reflect stablecoin classification change in TS package
> Custom tagging of trading pairs

- tradeexecutor/analysis/trade_analyser.py
- Simplify `calculate_summary_statistics_for_positions()` as the method is gigantic and hard to manage
- Separate current logic of calculating time in market to its own method, also simplify the logic
Part of #1064
> Refactor time in market calculation

- tests/mainnet_fork/test_enzyme_credit_position.py
- tradeexecutor/cli/commands/check_position_triggers.py
- tradeexecutor/cli/main.py
- tradeexecutor/strategy/runner.py
Swap order of sync interests and sync treasure so deposit/redemption can't mess up the calculation of interests
Might be related to #1003
> Change order of sync interests

- tests/backtest/test_token_tax.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py
- tests/mainnet_fork/test_enzyme_guard_credit_positions.py
- tests/test_binance_data.py
- tradeexecutor/backtest/backtest_runner.py
- tradeexecutor/state/identifier.py
- tradeexecutor/state/trade.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/pandas_trader/strategy_input.py
- tradeexecutor/strategy/parameters.py
- tradeexecutor/strategy/pricing_model.py
- tradeexecutor/strategy/runner.py
- tradeexecutor/strategy/trading_strategy_universe.py
- tradeexecutor/strategy/universe_model.py
- Add `load_partial_data(pair_extra_metadata=True)` to fetch token tax data, among other TokenSniffer metadata
- [See limitations here](https://github.com/tradingstrategy-ai/trading-strategy/blob/8900173a6b17a57c380335554867f4843b4256f8/tradingstrategy/utils/token_extra_data.py#L9), and this is put together
> Slippage tolerance using token tax

- tests/backtest/test_indicator.py
- tests/mainnet_fork/test_enzyme_credit_position.py
- tests/web/test_webhook_api.py
- tradeexecutor/state/identifier.py
- tradeexecutor/strategy/pandas_trader/indicator.py
- Having both Uni v2 and v3 pair at the same time broken indicator cache
- Fix `TradingPairIdentifier.__eq__` to consider fee
> Tag pair fee in indicator cache

- strategies/test_only/memecoin_index.py
- tradeexecutor/strategy/pandas_trader/indicator.py
- Set `series.attrs["error"]` or `df.attrs["error"]` when we raise an exception or get no data when generating indicators
- Tune down logging level of these errors, as they break the Discord logger
> On indicator data generation, record the error

- tests/backtest/test_indicator.py
- tradeexecutor/strategy/pandas_trader/indicator.py
- tradeexecutor/strategy/pandas_trader/runner.py
- Expose `timestamp` and `execution_context` for indicator calculations
- Needed for forward-filled indicators
- Create an example of `tvl` indicator that is forward filled
> More indicator parameters

- poetry.lock
- pyproject.toml
- tests/mainnet_fork/test_velvet_e2e.py
- tradeexecutor/cli/close_all.py
- tradeexecutor/cli/commands/check_accounts.py
- tradeexecutor/cli/commands/check_position_triggers.py
- tradeexecutor/cli/commands/check_wallet.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/cli/commands/init.py
- tradeexecutor/cli/commands/reset.py
- tradeexecutor/cli/commands/reset_deposits.py
- tradeexecutor/cli/testtrade.py
- tradeexecutor/ethereum/enzyme/vault.py
- tradeexecutor/ethereum/velvet/vault.py
- tradeexecutor/strategy/sync_model.py
- Add `correct-accounts` CLI command for Velvet
- Factor `SyncModel` a bit because Velvet vaults are identified by portfolio address, not vault address
- Bump `pyramid-openapi3` to the latest
- Fix https://github.com/lepture/mistune/issues/403
> correct-accounts for Velvet

- tradeexecutor/cli/loop.py
- tradeexecutor/strategy/runner.py
- We need to have up-to-date valuations to process Lagoon deposit/redemption queue in `sync_treasury`
> Change order of portfolio revalue and treasury sync actions for Lagoon

- strategies/test_only/base-memecoin-index.py
- tests/cli/test_close_position.py
- tests/test_strategy_cycle_trigger.py
- tradeexecutor/cli/close_position.py
- tradeexecutor/cli/commands/close_position.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/main.py
- tradeexecutor/ethereum/execution.py
- tradeexecutor/strategy/execution_model.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- Add `PositionManager.check_enough_cash()`
- Looks like the cause for confusion in `base-memex` trade execution was that we have two spot positions open for the same token
- This should not happen normally, but might have happened during the ramp up phase as the strategy was still having execution issues
- Add CLI command `close-position
- Do manual wind up of unwanted open positions from CLI
> Tripwires and debug

- tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py
- tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py
- tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py
- tests/ethereum/test_uniswap_live_stop_loss.py
- tests/ethereum/test_uniswap_v3_live_stop_loss.py
- tests/mainnet_fork/aave_v3/test_aave_v3_live_credit_supply.py
- tests/mainnet_fork/test_enzyme_guard_perform_test_aave_v3.py
- tradeexecutor/cli/close_position.py
- tradeexecutor/cli/commands/close_all.py
- tradeexecutor/cli/commands/close_position.py
- tradeexecutor/cli/loop.py
- tradeexecutor/statistics/core.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- tradeexecutor/strategy/valuation_update.py
- tradeexecutor/testing/simulated_execution_loop.py
- Refactor valuation so that it can be more easily called outside the main loop
- Needed for `close-position` command on Lagoon vault
> Refactor position valuation to its own module for reusability

- tradeexecutor/cli/commands/start.py
- tradeexecutor/ethereum/lagoon/vault.py
- tradeexecutor/state/position.py
- tradeexecutor/strategy/interest.py
- Lagoon vault valuation sync could not complete, because it thought the timestamp is too old
> Fix last valuation timestamp read for Aave positions

- .github/workflows/test-slow.yml
- tests/backtest/test_min_tvl_universe.py
- tradeexecutor/backtest/preprocessed_backtest.py
- Add script to generate some well-known backtesting history datasets
> Preprocessed backtest datasets

- strategies/test_only/base-ath.py
- tests/cli/test_cli_trading_pair.py
- tradeexecutor/cli/commands/check_universe.py
- tradeexecutor/cli/commands/shared_options.py
- tradeexecutor/cli/commands/trading_pair.py
- tradeexecutor/cli/main.py
- tradeexecutor/cli/universe.py
- tradeexecutor/state/identifier.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Add `trading-pair` CLI command
- Allow diagnose and flush caches for individual trading pair
- Most useful for checking CoinGecko, TokenSniffer and such data
> Add CLI trading pair debug command

- tests/backtest/test_backtest_inline_real_data.py
- tests/mainnet_fork/test_strategy_fetch_tvl.py
- tradeexecutor/analysis/curve.py
- tradeexecutor/analysis/multi_asset_benchmark.py
- tradeexecutor/backtest/tearsheet.py
- tradeexecutor/cli/commands/backtest.py
- tradeexecutor/cli/commands/shared_options.py
- tradeexecutor/utils/notebook.py
- Many capital allocators need daily returns CSV to evaluate strategies
> Automatically export backtest results as CSV

- .github/workflows/test-slow.yml
- .github/workflows/test.yml
- tests/mainnet_fork/test_check_accounts_low_value_position.py
- tests/mainnet_fork/test_correct_credit_position_redemption.py
- tests/mainnet_fork/test_correct_interest_not_accrued.py
- tests/strategy_tests/test_pancake_momentum_v2.py
- tests/web/test_webhook_main_loop_crash.py
- tradeexecutor/cli/commands/check_accounts.py
- tradeexecutor/cli/commands/correct_accounts.py
- tradeexecutor/ethereum/vault/vault_routing.py
- tradeexecutor/strategy/account_correction.py
- tradeexecutor/strategy/dust.py
- For positions that have left dust behind on close, implement a USD value based filtering so that these positions to not reappear on `correct-accounts` command when the dust forces to reopen the position by noticing there is token left
- The filter needs to be USD-based because token quantity can be high in 100ks even though tokens are worthless
> More dust position checks

- tests/backtest/test_forward_fill.py
- tradeexecutor/analysis/pair.py
- tradeexecutor/cli/loop.py
- tradeexecutor/strategy/pandas_trader/runner.py
- tradeexecutor/strategy/trading_strategy_universe.py
- Display universe without forward filled dates for price data to diagnose issues
- After startup, check the universe age and refuse to startup on too old data
> Display universe, ignore forard fill

- tests/velvet/test_velvet_check_enter_position.py
- tradeexecutor/ethereum/vault/vault_routing.py
- tradeexecutor/strategy/asset.py
- tradeexecutor/strategy/pandas_trader/position_manager.py
- Vault share token mismatch was not correctly accounted for Spark USD vault
> Check accounts vault

- tradeexecutor/ethereum/vault/vault_valuation.py
- tradeexecutor/state/valuation.py
- tradeexecutor/strategy/pandas_trader/yield_manager.py
- When converting to sell quantity, the vault share token price was inverted, leading to too high quantity number
> Vault share token price was calculated wrong way

- .github/workflows/test-slow.yml
- .github/workflows/test.yml
- tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py
- tests/lagoon/test_lagoon_e2e.py
- tests/lagoon/test_lagoon_e2e_binance.py
- tests/mainnet_fork/test_enzyme_credit_position.py
- tests/mainnet_fork/test_repair_vault_deposit.py
- tradeexecutor/cli/commands/check_universe.py
- tradeexecutor/cli/commands/start.py
- tradeexecutor/cli/commands/trading_pair.py
- tradeexecutor/cli/universe.py
- tradeexecutor/ethereum/wallet.py
- When `create_trading_universe()` is run through CLi `check-universe` command, it has access to web3 connection and can perform all kinds of onchain checks about trading pairs in this step
> Allow check-universe command to access executoin model and web3 connection

- tradeexecutor/monkeypatch/plotly.py
- tradeexecutor/visual/image_output.py
fix #1235
- Monkey patch Plotly `Figure.to_dict()` instead of `Figure.show()` (`to_dict` is used when rendering charts for notebooks AND web renderer)
- Refactor: use `Figure.to_image()` instead of `Kaleido.write_fig()` (less code, still uses Kaleido under the hood)
This is difficult to test in an automated way – probably not worth the effort. I was able to manually test both code paths (notebooks and web renderer) – this solution works for both.
> Fix Plotly x-axis date labels
