tradingstrategy-ai/trade-executor

strategies/bnb_chain_16h_momentum.py, tests/ganache/test_bnb_chain_16h_momentum.py, tests/test_state.py, tests/test_uniswap_live_pricing.py, tradeexecutor/cli/loop.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/hot_wallet_sync.py, tradeexecutor/ethereum/uniswap_v2_live_pricing.py, tradeexecutor/ethereum/uniswap_v2_valuation.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/state/statistics.py, tradeexecutor/statistics/core.py, tradeexecutor/strategy/qstrader/order_sizer.py, tradeexecutor/strategy/qstrader/portfolio_construction_model.py, tradeexecutor/strategy/tick.py, tradeexecutor/strategy/trading_strategy_universe.py
Various fixes found out when implementing 16h cycle strategy.
=> Bnb 16h strat

scripts/prepare-new-docker.sh, strategies/bnb_chain_16h_momentum.py, strategies/pancake_8h_momentum.py, tests/ganache/test_forked_bnb_chain_pancake.py, tests/ganache/test_uniswap_v2_routing.py, tests/strategies/frozen_asset.py, tests/strategies/pancakeswap_v2_main_loop.py, tests/test_cli_approval.py, tests/test_ethereum_tester_trade.py, tests/test_uniswap_live_pricing.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/uniswap_v2_execution.py, tradeexecutor/ethereum/uniswap_v2_execution_v0.py, tradeexecutor/ethereum/uniswap_v2_routing.py, tradeexecutor/state/state.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/execution_model.py, tradeexecutor/testing/ethereumtrader.py
Move max slippage out from router 
- To execution model
- Have it set per trade and on the state, so it is can be easily diagnosed
=> Max slippage per trade

tradeexecutor/strategy/cycle.py
=> Add supporot for more trade cycle durations

README.md, poetry.lock, tests/test_backtest_execution_three_way.py, tradeexecutor/strategy/trading_strategy_universe.py
Add `load_pair_data_for_single_exchange()` to construct single or limited pair trading universe. This function uses JSONL data endpoint to download trading pair data only for a single pair. This avoids the out of memory issues that decompressing a large Parquet file may cause.
=> Low memory data loading

.github/workflows/tests.yml
* Add correct cache to test job
* Add build job to build docker image and push to registry
=> Use cache for test then build

tests/ganache/test_bnb_chain_16h_momentum.py, tests/ganache/test_ema_crossover.py, tests/ganache/test_forked_bnb_chain_pancake.py, tests/ganache/test_main_loop.py, tests/ganache/test_pancake_8h_momentum.py, tests/ganache/test_quickswap_momentum.py, tests/test_data_age.py, tradeexecutor/backtest/backtest_pricing.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/loop.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/uniswap_v2_live_pricing.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/qstrader/portfolio_construction_model.py, tradeexecutor/strategy/trading_strategy_universe.py
- Improve dataset management in unit tests - avoid unnecessary redownloads
- Fix some legacy pair issues caused by problems with internal ids
=> Fix bad pairs and slow tests

strategies/ema-crossover-long-only-no-stop-loss.py, strategies/pancake-momentum-v2.py, tests/test_trading_universe.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/testing/synthetic_exchange_data.py, tradeexecutor/utils/typing.py
- Add `TradingStrategyUniverse.create_multipair_universe`
- Add optimised `PandasPairUniverse.build_index`
=> Multipair universe

strategies/pancake-momentum-v2.py, tests/test_backtest_execution.py, tests/test_backtest_execution_three_way.py, tests/test_rebalance.py, tests/test_trading_universe.py, tradeexecutor/ethereum/default_routes.py, tradeexecutor/state/identifier.py, tradeexecutor/state/portfolio.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/rebalance.py, tradeexecutor/testing/synthetic_price_data.py
Add rebalance module for developing multipair trading strategies.
=> Rebalance module

.github/workflows/tests.yml, README.md, docs/install.md, docs/testing.md, poetry.lock, pyproject.toml, strategies/test_only/random_eth_usdc.py, tests/ganache/test_bnb_chain_16h_momentum.py, tests/ganache/test_forked_bnb_chain_pancake.py, tests/ganache/test_frozen_position_and_blacklist.py, tests/ganache/test_main_loop.py, tests/ganache/test_pancake_8h_momentum.py, tests/ganache/test_quickswap_momentum.py, tests/test_cli_approval.py, tests/test_ethereum_tester_trade.py, tradeexecutor/ethereum/default_routes.py, tradeexecutor/strategy/qstrader/__init__.py, tradeexecutor/strategy/trading_strategy_universe.py
-Removing and cleaning up dependencies
=> Preparing 0.1.0 release

poetry.lock, pyproject.toml
- Needed to produce some (not all) PnL analysis 
- Hopefully remove later if possible
=> Add matplotlib as explicit dependency

notebooks/pancakeswap-ema-stop-loss.ipynb, poetry.lock, pyproject.toml, tests/test_backtest_execution_three_way.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/trading_strategy_universe.py
Added a PancakeSwap strategy example using stop loss.
=> Stop loss example real data

poetry.lock, pyproject.toml, tests/test_uniswap_live_stop_loss.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/log.py, tradeexecutor/cli/loop.py, tradeexecutor/cli/main.py, tradeexecutor/strategy/cycle.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/runner.py, tradeexecutor/testing/simulated_execution_loop.py, tradeexecutor/utils/blockchain.py
- Add stop loss support using Uniswap v2 compatible price feeds
=> Live stop loss support

tradeexecutor/backtest/backtest_runner.py, tradeexecutor/visual/single_pair.py
Add percentage to candle stick hover info on visualise_single_pair
=> Candle info

.github/workflows/client-side.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml
=> Fix broken master

tradeexecutor/visual/single_pair.py
=> fix candlestick percentages

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/cli/loop.py, tradeexecutor/state/validator.py, tradeexecutor/utils/timestamp.py
- We were leaking `pd.Timestamp` objects to the state
=> Fix further serialization issues

env/pancake-eth-usd-sma.env, tradeexecutor/cli/main.py, tradeexecutor/cli/prepare_docker_env.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/hot_wallet_sync.py, tradeexecutor/ethereum/tx.py, tradeexecutor/ethereum/web3config.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/execution_model.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/universe_model.py
- Execute trades against a live blockchain with real money to see everything works before launching a strategy
=> Perform a test trade command line command

strategies/test_only/crash.py, tests/test_execution_state.py, tests/test_ring_buffer_logger.py, tests/test_ring_buffer_logging_handler.py, tests/test_webhook_api.py, tests/test_webhook_auth.py, tests/test_webhook_main_loop_crash.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/init.py, tradeexecutor/cli/log.py, tradeexecutor/cli/loop.py, tradeexecutor/state/metadata.py, tradeexecutor/strategy/execution_state.py, tradeexecutor/utils/ring_buffer_logging_handler.py, tradeexecutor/webhook/api.py, tradeexecutor/webhook/app.py, tradeexecutor/webhook/server.py
Instead of crashing the trade executor webhook on a trade failure (Python exception), expose this exception through /status endpoint.
Addresses #87
=> Webhook /status endpoint

tests/test_default_routes.py, tradeexecutor/ethereum/default_routes.py, tradeexecutor/ethereum/uniswap_v2_routing.py, tradeexecutor/strategy/default_routing_options.py, tradeexecutor/strategy/execution_context.py
- Clean up the code so that other people can start adding routes
-  Adding tests. 
- Adding Uniswap v2 routing.
=> Cleaning up routing.

strategies/ema-crossover-long-only-no-stop-loss.py, tests/ganache/test_ema_crossover.py, tests/test_cli_commands.py, tests/test_webhook_api.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/commands/__init__.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/bootstrap.py, tradeexecutor/strategy/description.py, tradeexecutor/strategy/execution_state.py, tradeexecutor/strategy/strategy_module.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/visual/inline_image.py, tradeexecutor/webhook/api.py
Add the endpoint that returns the strategy source code.
=> Adding /source endpoint

tests/test_summary_statistics.py, tradeexecutor/cli/loop.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/statistics.py, tradeexecutor/statistics/summary.py, tradeexecutor/strategy/run_state.py, tradeexecutor/strategy/summary.py, tradeexecutor/webhook/api.py
- Add calculation of strategy summary statistics to be used on summary tiles
- Hook in the stats calculation to the live position statistics engine
=> Summary stats

tests/test_default_routes.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/strategy/default_routing_options.py, tradeexecutor/strategy/reserve_currency.py
- added routing support for trader joe on avalanche and quickswap on polygon
- added additional stable coins to be used as reserve currencies
Queries: 
- didn't add DAI as possible quote token, not sure if it is a quote token, do I need to add it? 
- added 0x in front for some of the `init code hashes` as I saw one of the pre-existing init codes had a 0x, is that fine?
=> Adding routing support for additional exchanges

scripts/update-deps.sh, tradeexecutor/ethereum/tx.py, tradeexecutor/strategy/runner.py
Cut useless output when there are no new trades
=> Reduce log output when there are no trades

tests/test_webhook_api.py, tradeexecutor/strategy/run_state.py, tradeexecutor/webhook/api.py
- Export full `RunState` object making code maintenance easier
=> Export full run state

tests/test_cli_commands.py, tradeexecutor/cli/init.py, tradeexecutor/cli/loop.py
- How to crash gracefully with APSCheduler
- Add extra checks to prevent London gas price method leaking into BSC
=> Scheduler exception handler

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/tx.py, tradeexecutor/ethereum/uniswap_v2_live_pricing.py, tradeexecutor/state/statistics.py, tradeexecutor/strategy/stop_loss.py
=> Freeze the TradeSummary class to ensure no attributes with wrong name are set 

tradeexecutor/backtest/backtest_execution.py
=> Fix buy/sell markers not showing

tests/test_cli_commands.py, tradeexecutor/cli/commands/console.py, tradeexecutor/cli/commands/version.py, tradeexecutor/cli/main.py
- Open interactive Python prompt to diagnose state, universe and web3 connection issues
=> Add console command

tradeexecutor/ethereum/execution.py, tradeexecutor/state/blockhain_transaction.py
- Polygon is misbehaving again
=> Add log messages to help to resolve broadcasting failed situations

tests/test_state.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py
- Record portfolio value when the position is open, so we can easily calculate (historical) risk of any past position
- Add risk calculations for the position open value
=> Added position size risk calculation, attempt 3

tradeexecutor/state/visualisation.py, tradeexecutor/visual/single_pair.py
Add support for creating stop loss indicators. See this [question](https://community.plotly.com/t/show-gaps-in-px-line-when/34964/2).
Fixes #151
=> Stop loss line

tradeexecutor/analysis/trade_analyser.py
small fix to `max_pos_cons` stat
=> max positive consecutive bug fix

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/visual/single_pair.py
- add trading fee to buy/sell text labels on charts (works for backtesting)
=> Add swap fee info to trade chart and table

docs/visual-studio-code-docker-dev-container-for-jupyter-notebooks.md, strategies/test_only/pancakeswap_v2_main_loop.py, tests/test_decision_trigger.py, tradeexecutor/strategy/pandas_trader/decision_trigger.py
Cleaning up terminology and confusion between strategy decision timestamp and last possible candle timestamp
=> Adjust for one candle time frame delay when waiting for the trigger

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/state/trade.py
- Make it possible to flag bad historical data from previous executors
- Work around old trades not having mid_price
=> Bad data issues

tradeexecutor/cli/loop.py
=> Fix IOPub data rate exceeded in Jupyter notebook when using PyCharm

tests/test_legacy_state_dump.py, tradeexecutor/state/identifier.py, tradeexecutor/state/types.py, tradeexecutor/strategy/reverse_universe.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/strategy/universe_model.py
- Allow easily get the trading data for an existing trade execution state
=> Add reverse_trading_universe_from_state()

tests/mainnet_fork/test_ema_crossover.py, tests/mainnet_fork/test_main_loop.py, tests/mainnet_fork/test_uniswap_v2_routing.py, tests/test_uniswap_live_stop_loss.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/qstrader/runner.py, tradeexecutor/strategy/runner.py
- Fix the internal API issues where wall clock time and strategy cycle timestamp had been confused, causing strategy to not to execute trades correctly
- Rip off some remaining Ganache code
=> Fix strategy cycle timestamp usage

README.md, strategies/pancake-momentum-v2.py, strategies/test_only/pancake-momentum-weekly.py, tests/strategy_tests/test_pancake_momentum_v2.py, tests/test_rebalance.py, tests/test_strategy_cycle_trigger.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/strategy/cycle.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/rebalance.py, tradeexecutor/strategy/runner.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/python_module_loader.py
Add it initial logic to make portfolio construction model strategies.
=> Add portfolio construction model and weight based rebalances

tests/test_state.py, tradeexecutor/monkeypatch/dataclasses_json.py, tradeexecutor/strategy/pricing_model.py
- Add support for serialising `timedelta` objects
=> Timedelta json serialisation

tests/test_state.py, tradeexecutor/analysis/trade_analyser.py
Rebased and fixed https://github.com/tradingstrategy-ai/trade-executor/pull/204
=> Return percent fix

tradeexecutor/backtest/backtest_routing.py
Cleans unused methods in `BacktestRoutingState` and `BacktestRoutingModel`
=> clean backtesting methods

tests/test_routing_data.py, tradeexecutor/ethereum/routing_data.py
- Add test coverage for routing_data.py (fixes #219)
- Also makes some small, necessary additions to routing_data.py. These missing lines were highlighted during testing
=> Routing data tests

tradeexecutor/analysis/trade_analyser.py
- silence warnings from pandas method
- silence warnings from quantstats package
=> silence warnings

tradeexecutor/analysis/trade_analyser.py
- Have added some comments and update text descriptions for statistics with potentially confusing names
- `# postion` indicates that the statistics actually refers to a position, not a trade
- Have created https://github.com/tradingstrategy-ai/trade-executor/issues/268 to fix this properly in the future
=> fix TradeSummary text desriptions and add comments

poetry.lock, pyproject.toml, tests/conftest.py, tests/enzyme/conftest.py, tests/enzyme/test_enzyme_deposit.py, tests/enzyme/test_enzyme_trade.py, tests/mainnet_fork/test_uniswap_v3_routing.py, tests/test_execute_trade_uniswap.py, tests/test_execute_trade_uniswap_v3.py, tests/test_legacy_repair.py, tests/test_legacy_state_dump.py, tests/test_state.py, tests/test_transaction_builder.py, tradeexecutor/ethereum/enzyme/tx.py, tradeexecutor/ethereum/ethereumtrader.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/ethereum/routing_state.py, tradeexecutor/ethereum/tx.py, tradeexecutor/ethereum/uniswap_v2_routing.py, tradeexecutor/ethereum/uniswap_v3_routing.py, tradeexecutor/state/blockhain_transaction.py, tradeexecutor/state/trade.py, tradeexecutor/testing/ethereumtrader_uniswap_v2.py, tradeexecutor/testing/pytest_helpers.py
- Add trade execution through Enzyme's vault
=> Enzyme vault execution

README.md, tests/strategy_tests/test_defi_bluechip.py, tests/test_rebalance.py, tradeexecutor/analysis/alpha_model_analyser.py, tradeexecutor/analysis/multipair.py, tradeexecutor/strategy/alpha_model.py
- Add `tradeexecutor.analysis.alpha_model_analyser.analyse_alpha_model_weights` and `create_pair_weight_analysis_summary_table`
- Reworked how the alpha model stores signals. Keep raw signals around so we can analyse them later
=> Adding a summary table to analyse alpha model weights

tests/backtest/test_backtest_inline_synthetic_data.py, tests/backtest/test_backtest_open_position.py, tradeexecutor/analysis/trade_analyser.py
- Currently, if there is an open position left at the end of the backtest, there is an error raised when calling `expand_timeline` or `expand_timeline_raw`, this PR fixes that
- Adds tests to ensure doesn't happen again
=> fix open position bug

tests/backtest/test_grid_search.py, tradeexecutor/analysis/grid_search.py, tradeexecutor/backtest/grid_search.py
- Add heatmaps for the grid search output
=> More grid search

tradeexecutor/visual/benchmark.py, tradeexecutor/visual/single_pair.py
=> fix benchmark timestamp

env/local-test.env, strategies/test_only/enzyme_end_to_end.py, strategies/test_only/pancakeswap_v2_main_loop.py, tests/enzyme/conftest.py, tests/enzyme/test_enzyme_end_to_end.py, tests/test_webhook_main_loop_crash.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/check_wallet.py, tradeexecutor/cli/commands/console.py, tradeexecutor/cli/commands/init.py, tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/reserve.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/sync_model.py
- Fix `perform-test-trade` CLI command to use the new sync model
=> More work on Enzyme test trades

poetry.lock, pyproject.toml, tests/enzyme/test_enzyme_webhook_api.py, tests/test_cli_commands.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/check_wallet.py, tradeexecutor/cli/commands/start.py, tradeexecutor/ethereum/hot_wallet_sync_model.py, tradeexecutor/state/metadata.py, tradeexecutor/state/position.py, tradeexecutor/strategy/default_routing_options.py, tradeexecutor/strategy/summary.py, tradeexecutor/webhook/api.py
- Needed for the frontend deposit experience
=> Add Enzyme's smart contract to metadata

tests/units_tests/test_cross_over_under.py, tradeexecutor/state/crossover.py, tradeexecutor/strategy/trading_strategy_universe.py
- Adds additional functionality to crossover functions
- `lookback_period` -> specifies the range in which crossover is allowed to occur, so it doesn't always have to only be at the latest iteration
- `must_return_index` -> if true, returns the index of the crossover as well
- Adds notebook for momentum strategy demonstrating more complex crossover logic
- Fixes #317
=> Crossover fix

poetry.lock, pyproject.toml, scripts/manual-visualisation-test.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/execution.py
- The first attempt to address the issue
=> Fix Uniswap v3 price being inverse

tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/hot_wallet_sync_model.py, tradeexecutor/strategy/runner.py, tradeexecutor/strategy/sync_model.py
- Handle error situations when private key has been used outside `trade-executor`
=> Nonce resync

tradeexecutor/cli/loop.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/runner.py
- Do not wait for strategy cycle to update visualisations, etc. and make them available right after the webhook starts
=> Early init of run state

tests/test_webhook_main_loop_crash.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/pandas_trader/runner.py
- Refresh was calling Discord post
=> Fix Discord visualisation post

tests/backtest/test_backtest_position_trigger.py, tradeexecutor/strategy/pandas_trader/position_manager.py
- Adds `stop_loss_usd` support
- Adds tests for write, read, and trigger
- Fixes #363
=> Stop-loss-usd

tradeexecutor/cli/loop.py, tradeexecutor/state/statistics.py, tradeexecutor/state/visualisation.py
=> Add rolling profit to progress bar

strategies/test_only/enzyme_end_to_end.py, tests/enzyme/conftest.py, tests/enzyme/test_enzyme_end_to_end.py, tests/units_tests/test_parse_data.py, tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/universe.py, tradeexecutor/strategy/trading_strategy_universe.py
- Allows perform-test-trade to be performed on multipair universes
- Related to https://github.com/tradingstrategy-ai/trading-strategy/pull/101
=> Add multipair support for perform-test-trade

tests/enzyme/test_enzyme_end_to_end.py, tests/strategy_tests/test_defi_bluechip.py, tradeexecutor/cli/commands/init.py, tradeexecutor/cli/commands/reinit.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/state/balance_update.py, tradeexecutor/state/reserve.py, tradeexecutor/utils/timestamp.py
- Create `reinit` CLI command to force resync balances
=> Vault forced on-state balance repair

pytest.ini, tests/test_strategy_state_visualisation_multipair.py, tests/units_tests/test_on_balance_volume.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/testing/synthetic_pair_data.py, tradeexecutor/visual/custom_indicators.py, tradeexecutor/visual/strategy_state.py
- Add support for multipair strategy live visualisations for up to 3 pairs
- Fixes #378
=> Multipair live visualisations

tests/backtest/test_backtest_profit_calculation.py, tests/test_summary_and_metrics.py, tests/test_webhook_main_loop_crash.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/state/metadata.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/state.py, tradeexecutor/state/store.py, tradeexecutor/statistics/key_metric.py, tradeexecutor/statistics/summary.py, tradeexecutor/strategy/summary.py, tradeexecutor/visual/equity_curve.py
- Expose real-time sharpe, sortino, max drawdown to the frontend
- Use backtested data when we do not have enough live trading history
=> Add strategy ley metric calculations

tradeexecutor/analysis/multipair.py
=> make links clickable

.gitignore, poetry.lock, pyproject.toml, scripts/pyodide/README.md, scripts/pyodide/index.html, tests/test_equity_curve.py, tests/test_summary_and_metrics.py, tests/test_webhook_api.py, tradeexecutor/backtest/notebook.py, tradeexecutor/statistics/summary.py, tradeexecutor/strategy/summary.py, tradeexecutor/visual/web_chart.py, tradeexecutor/webhook/api.py
- Add `web_chart` endpoint to offer data exports for various charts to the frontend
=> Chart data endpoint

poetry.lock, pyproject.toml, tests/enzyme/test_enzyme_uniswap_v3_mainnet_fork.py, tradeexecutor/ethereum/enzyme/vault.py
- Use lazy timestamp reading for vault events unless we know we are connected to the JSON-RPC node, which we knows supports mass timestamp ingesting
=> Lazy timestamp reader

tests/enzyme/test_enzyme_correct_accounting.py, tests/enzyme/test_enzyme_end_to_end.py, tests/enzyme/test_enzyme_uniswap_v3_mainnet_fork.py, tradeexecutor/analysis/position.py, tradeexecutor/cli/commands/check_accounting.py, tradeexecutor/cli/commands/check_accounts.py, tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/revert.py, tradeexecutor/state/position.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/account_correction.py
- Display an output of on-chain balance and internal state balance differences 
- Show revert reason in `show-positions` CLI command
=> Added check-accounts command

tradeexecutor/state/position.py
- Due to rounding errors position might not be closed for a zero value
- When a position is closed, do not check for zero but check for the dust amount
=> Add dust check for close position

tests/test_strategy_state_visualisation_multipair.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/visual/strategy_state.py
- No real changes to output
- Just adds some extra arguments to `draw_multipair_strategy_state`
- Couldn't find bug for why live images are squished (since it works in testing) #462
=> Multipair-viz-3

tradeexecutor/strategy/output.py
=> fix profit reporting

scripts/analyse-reserve.ipynb, tests/backtest/test_backtest_execution.py, tests/backtest/test_backtest_execution_three_way.py, tests/ethereum/test_execute_trade_uniswap_v3.py, tests/mainnet_fork/test_uniswap_v2_routing.py, tests/mainnet_fork/test_uniswap_v3_routing.py, tradeexecutor/analysis/position.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/commands/reinit.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution_v0.py, tradeexecutor/state/balance_update.py, tradeexecutor/state/generic_position.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py, tradeexecutor/state/repair.py, tradeexecutor/state/reserve.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/testing/ethereumtrader_uniswap_v2.py, tradeexecutor/testing/ethereumtrader_uniswap_v3.py, tradeexecutor/testing/pairuniversetrader.py, tradeexecutor/testing/simulated_trader.py, tradeexecutor/visual/utils.py
- Add more diagnostics to reserve calculations
- Improve naming of some of trading position related function names and documentation
- Moved more function`GenericPosition`
- Still need another round of debugging to get bottom of the issues with wrong reserve balances
=> Reserve position diagnostics

poetry.lock, pyproject.toml, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_live_pricing.py
- Track the block number for the live price structure we use in buy/sell amount and slippage calculations
- This allows us to diagnose post-mortem why slippage did exceeded our expectations when the trade was executed
=> Track the source block of a price

poetry.lock, pyproject.toml, tradeexecutor/ethereum/enzyme/vault.py
Workaround QuickNode API limitations and issues
=> Quicknode sucks

tradeexecutor/cli/discord.py
=> fix discord timeout

tests/test_summary_and_metrics.py, tradeexecutor/state/reserve.py, tradeexecutor/state/sync.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/visual/equity_curve.py
- Aims to fix test suite warnings on trade-executor
- The remaining warnings are due to external packages
- See previous attempt #377
- Fixes #379
=> fix warnings

scripts/analyse-balance-events.ipynb, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/state/sync.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/runner.py
- Check account balances on startup and after each strategy treasury sync
- Abort trade execution if there is an account balance mismatch detectd
=> Adding the extra accounting checks for live trading

tradeexecutor/backtest/backtest_runner.py, tradeexecutor/backtest/report.py
=> update error message

scripts/analyse-failed-trades.ipynb, tests/enzyme/test_enzyme_correct_accounting.py, tradeexecutor/backtest/backtest_sync.py, tradeexecutor/cli/commands/check_accounts.py, tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/hot_wallet_sync_model.py, tradeexecutor/state/blockhain_transaction.py, tradeexecutor/state/generic_position.py, tradeexecutor/state/position.py, tradeexecutor/state/reserve.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/sync_model.py
- Add `check-accounts` command for hot wallet based deployments
- Add `correct-accounts` command for hot wallet based deployments
=> Enable check-accounts command for hot wallets

poetry.lock, pyproject.toml, scripts/analyse-historical-uniswap-v3-price.py, tests/backtest/test_backtest_ema_crossover.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_live_pricing.py, tradeexecutor/strategy/trade_pricing.py
- Corretly pass `max_slippage` around
=> Fix using wrong slippage 1 BPS instead of the given value

tests/backtest/test_backtest_ema_crossover.py, tests/enzyme/test_enzyme_correct_accounting.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_live_pricing.py
- Read per-block mid-price to be more accurate with the records
- Fix issues with backtest tests
=> Adding mid-price read directly from the chain

tests/ethereum/test_aave_v3_interest.py, tradeexecutor/ethereum/aave_v3/interests.py
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/497
=> Aave - estimate borrow interest using candle

tests/backtest/test_backtest_result_visualisation.py, tests/test_strategy_state_visualisation_multipair.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/visual/multiple_pairs.py, tradeexecutor/visual/single_pair.py, tradeexecutor/visual/strategy_state.py, tradeexecutor/visual/technical_indicator.py, tradeexecutor/visual/utils.py
- Fixes #512 
- Also fixed bug of `technical_indicators` parameter not working properly
=> Allow no detached indicators

.github/workflows/test-slow.yml, tests/test_state.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_live_pricing.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_live_pricing.py, tradeexecutor/state/position.py, tradeexecutor/state/statistics.py, tradeexecutor/state/trade.py, tradeexecutor/statistics/core.py, tradeexecutor/statistics/summary.py
- Make sure `update_statistics` is deterministically calculated at the end of each trading cycle
- Adding more logging and diagnostics and asserts to position statistics calculations
- Related to https://github.com/tradingstrategy-ai/trade-executor/issues/517
=> Position stats fixes

tests/test_default_routes.py, tests/test_routing_data.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/strategy/default_routing_options.py, tradeexecutor/strategy/reserve_currency.py, tradeexecutor/strategy/routing.py
- See https://arbitrumfoundation.medium.com/usdc-to-come-natively-to-arbitrum-f751a30e3d83
=> Separate USDC.e and USDC on Arbitrum

notebooks/arbitrum-btc-usd-sls-binance-data-1h.ipynb, tests/enzyme/test_enzyme_trade.py, tests/test_state.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/ethereum/execution.py, tradeexecutor/state/portfolio.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/dust.py
- Have a different dust epsilon for WBTC than other pairs
=> Adding dynamic dust epsilon per trading pair

tradeexecutor/visual/multiple_pairs.py
addresses #521 somewhat, although not a complete fix
=> disable multipair volume

tests/backtest/test_backtest_credit_supply_mock.py, tests/backtest/test_backtest_credit_supply_real_data.py, tradeexecutor/backtest/backtest_sync.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/interest.py
=> Interest calculation for backtest credit supply position

tests/test_summary_and_metrics.py, tradeexecutor/statistics/key_metric.py, tradeexecutor/strategy/summary.py
- Add `last_trade` and `trades_last_week` key metrics
=> Export last trade metrics to strategy tiles

tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py
previously, `asset_deltas` was being provided where the `gas_price_suggestion` should've been.
=> Test-trade-bug-fix-2

tests/test_ring_buffer_logging_handler.py, tradeexecutor/utils/ring_buffer_logging_handler.py
=> add formatted data property

tests/backtest/test_backtest_short_synthetic_data.py, tests/interest/test_state_short.py, tradeexecutor/state/identifier.py, tradeexecutor/state/loan.py, tradeexecutor/state/position.py, tradeexecutor/strategy/lending_protocol_leverage.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/testing/synthetic_universe_data.py, tradeexecutor/utils/leverage_calculations.py
* Use new `LeverageEstimate` to calculate sizes before opening the position
* Validate max leverage before open short position
* Calculate liquidation price and add to position
* Validate stoploss to make sure liquidation can't be reached
=> Short position validation

tests/backtest/test_backtest_short_synthetic_data.py, tests/interest/test_state_short.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/runner.py, tradeexecutor/strategy/stop_loss.py, tradeexecutor/testing/synthetic_lending_data.py, tradeexecutor/utils/leverage_calculations.py
Handle take profit and stop loss trigger for short positions
=> Handle short position trigger

tests/enzyme/test_enzyme_end_to_end.py, tradeexecutor/cli/backup.py, tradeexecutor/cli/commands/reset_deposits.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/sync_model.py
- Add a CLI command to get rid of bad deposit/redemption events that may prevent trade-executor to run correctly
=> Reset deposits

tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/trading_strategy_universe.py
=> Remove old bad workaround for single pair strats

tests/backtest/test_backtest_mixed_positions.py, tradeexecutor/state/position.py
Part of #579 
Fix some edge cases when mixing long and short positions in same strategy
=> Support mixed strategy

poetry.lock, pyproject.toml, tests/cli/test_cli_commands.py, tests/web/test_webhook_main_loop_crash.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/start.py, tradeexecutor/state/portfolio.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/runner.py
- Do not attempt to perform any trades is the trade executor does not have meaningful balances
- Bump to the latest eth_defi to work around LlamaNodes issues
=> Add trading capital check

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/visual/single_pair.py, tradeexecutor/visual/utils.py
Part of #581 
Fix visualization bugs for short positions and add some improvements
=> Improve visualization

.github/workflows/test-and-build-image.yml, .github/workflows/test-slow.yml, poetry.lock, pyproject.toml, tests/enzyme/conftest.py, tests/ethereum/test_hot_wallet_sync_model.py, tests/web/test_webhook_api.py, tests/web/test_webhook_auth.py, tests/web/test_webhook_main_loop_crash.py
=> Enable pytest-xdist

tests/backtest/test_backtest_short_synthetic_data.py, tradeexecutor/state/position.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/stop_loss.py
=> Trailing stop loss support for short position

tests/mainnet_fork/conftest.py, tests/mainnet_fork/test_uniswap_v2_polygon.py, tests/mainnet_fork/test_uniswap_v3_routing.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py, tradeexecutor/strategy/asset.py, tradeexecutor/strategy/pandas_trader/position_manager.py
- Check accounts when doing three-way trades on a mainnet forked QuickSwap instance
=> [WIP] Three way trade test case

tests/mainnet_fork/test_uniswap_v2_polygon.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/state.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/runner.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/strategy/valuation.py
- Add more logging to diagnose problems with bad reserve calculations
- Add more test coverage (although it did not catch any bugs)
- Fix `check_accounts_post_trade` executed at the wrong phase
=> More polygon multipair debug

tests/backtest/test_backtest_inline_synthetic_data.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/utils/summarydataframe.py
=> change percentage to decimal

strategies/test_only/random_eth_usdc.py, tradeexecutor/ethereum/execution.py, tradeexecutor/strategy/bootstrap.py, tradeexecutor/strategy/runner.py
- Wait before doing post-execution accounting checks as some node providers may report stale data
=> Post execution 1 minute sleep

tests/backtest/test_backtest_inline_synthetic_data.py, tradeexecutor/analysis/trade_analyser.py
=> add separate stats for short and long

tests/enzyme/test_enzyme_correct_accounting.py, tradeexecutor/backtest/backtest_sync.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py, tradeexecutor/state/repair.py, tradeexecutor/state/state.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/asset.py, tradeexecutor/strategy/sync_model.py
- Be able to correct accounting for a position for which the size has gone zero due to external reasons
- Some cleanup and documentation on the state of closing positions
=> Account correction for zero-sized position

poetry.lock, pyproject.toml, tests/mainnet_fork/test_uniswap_v2_routing.py, tests/mainnet_fork/test_uniswap_v3_routing.py, tradeexecutor/ethereum/execution.py, tradeexecutor/testing/ethereumtrader_uniswap_v2.py, tradeexecutor/testing/ethereumtrader_uniswap_v3.py
- Add `broadcast_and_resolve_multiple_nodes`
=> Broadcast transactions using multiple nodes if possible

tradeexecutor/cli/loop.py
=> fix progress bar last iteration

poetry.lock, pyproject.toml, tests/backtest/test_backtest_inline_synthetic_data.py, tests/strategy_tests/test_defi_bluechip.py, tradeexecutor/analysis/multipair.py, tradeexecutor/analysis/trade_analyser.py
=> Summary table tooltips (links)

.github/workflows/test-and-build-image.yml
Create a PR from branch name `rc-*` to trigger build a special "release candidate" docker image for testing
=> Test build on PR

poetry.lock, pyproject.toml
- Significant internal updates to caching of RPC requests
=> Bump eth_defi to version 0.23

tests/ethereum/test_execute_trade_one_delta.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/one_delta/analysis.py, tradeexecutor/ethereum/one_delta/one_delta_execution.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/ethereum/routing_state.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_execution.py, tradeexecutor/testing/ethereumtrader_one_delta.py, tradeexecutor/testing/unit_test_trader.py
1delta routing and execution model
Close #671 
Close #672 
Part of #673
=> 1delta: routing model and execution model

README.md, scripts/pre-commit-sample/README.md, scripts/pre-commit-sample/pre-commit-checkfilesize.sample, scripts/pre-commit-sample/pre-commit-config.yaml, scripts/set-pre-commit-checkfilesize.sh
Script `set-pre-commit-checkfilesize.sh` will help to setup pre-commit file and active it
**Default: Max file size is 35MB**
=> Create pre-commit checkfilesize

tests/ethereum/test_execute_trade_one_delta.py, tests/ethereum/test_one_delta_live_short.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/ethereum/one_delta/one_delta_execution.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/one_delta/one_delta_valuation.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/testing/simulated_execution_loop.py
* Create 1delta valuation model
* Fix earlier problem with executing close position
* Add a live strategy test
Related to #673 and #677
=> 1delta test live strategy

tests/ethereum/polygon_forked/conftest.py, tests/ethereum/polygon_forked/test_generic_router.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_live_pricing.py, tradeexecutor/state/identifier.py, tradeexecutor/strategy/generic/generic_router.py, tradeexecutor/strategy/generic/routing_function.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/routing.py
- Open positions from the multiple protocols in the same state
- Ensure we have basic test coverage for GenericPosition code
=> GenericPosition: open positions

tests/ethereum/polygon_forked/test_one_delta_live_short.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/hot_wallet_sync_model.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/state/loan.py
Handle sync interests in hot wallet sync model
Related to #670 
Close #676
=> 1delta: hot wallet sync interest

tradeexecutor/visual/utils.py
=> fixes visualise_single_pair warning #691

poetry.lock, pyproject.toml, tests/enzyme/test_enzyme_end_to_end_multipair.py, tests/ethereum/polygon_forked/generic-router/test_generic_router.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/tx.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution.py, tradeexecutor/state/loan.py, tradeexecutor/strategy/runner.py
- Generic routing E2E test work
- Close multiple short positions test added
- Currently tests disabled, as more progress is needed to get them running
```
pytest -k test_generic_routing_close_position_across_markets
pytest -k test_generic_routing_live_trading_start  
```
=> Generic routing end-to-end integration execution run

tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tests/ethereum/polygon_forked/generic-router/test_generic_router.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/ethereum/test_execute_trade_one_delta.py, tests/interest/test_state_short.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/state/identifier.py, tradeexecutor/state/interest.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/strategy/lending_protocol_leverage.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/utils/accuracy.py
- Refactor updating executed amounts after short execution
- Withdraw all collateral from Aave if the trade is last close
- Add new epsilon for collateral calculation since it can be slightly off
=> Refactor update executed amounts

poetry.lock, pyproject.toml, tests/ethereum/test_gas_level.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/wallet.py, tradeexecutor/strategy/run_state.py
- Add another gas level measurement, which issues a warning instead of a halt
- Start with hardcoded 25 (MATIC)
=> Gas level warning

tradeexecutor/cli/commands/start.py, tradeexecutor/strategy/strategy_module.py
- Move user interface strategy element from env to the strategy module
=> Name, short, long description in strategy module

tests/strategy_tests/test_spot_short_bb.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/backtest/backtest_report_template.ipynb, tradeexecutor/cli/commands/backtest.py, tradeexecutor/cli/loop.py, tradeexecutor/cli/result.py, tradeexecutor/visual/benchmark.py
- Shuffle report items around
- Add side-by-side comparison
=> Update backtest report generator to support short-based strategies

tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/runner.py, tradeexecutor/testing/unit_test_trader.py
Increase / reduce short position size
Close #713
=> Adjust short position size

tests/enzyme/test_enzyme_correct_accounting.py, tests/web/test_webhook_main_loop_crash.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/log.py, tradeexecutor/webhook/app.py, tradeexecutor/webhook/events.py, tradeexecutor/webhook/server.py, tradeexecutor/webhook/web_log.py
- Log HTTP request and responses and timing to a separate log file for diagnostics
- Keep in a separate file, as we need to assume the main log output to be public
=> Web server logging

strategies/test_only/pandas_buy_every_second_day.py, tests/backtest/test_backtest_profit_calculation.py, tradeexecutor/statistics/key_metric.py
- Fixes profit calcution
- Adds test to ensure to different methods of calculating profit match
- Fixes https://github.com/tradingstrategy-ai/trade-executor/issues/747
- Fixes https://github.com/tradingstrategy-ai/frontend/issues/654
=> Fix profit calculation

tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tests/ethereum/polygon_forked/conftest.py, tests/ethereum/polygon_forked/generic-router/test_generic_router.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/ethereum/test_execute_trade_one_delta.py, tradeexecutor/ethereum/ethereum_protocol_adapters.py, tradeexecutor/ethereum/one_delta/one_delta_live_pricing.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/testing/ethereumtrader_one_delta.py
- Integrate 1delta quoter to closely estimate price
- Fix issue with position sizing adjustment
- Handle slippage when building transaction in routing
Close #739 and #740
=> 1delta quoter integration

tradeexecutor/state/statistics.py, tradeexecutor/statistics/core.py, tradeexecutor/statistics/statistics_table.py, tradeexecutor/statistics/summary.py, tradeexecutor/strategy/summary.py
=> move long short table to state.stats

tests/ethereum/test_uniswap_v3_live_stop_loss.py, tests/test_state.py, tradeexecutor/cli/loop.py, tradeexecutor/state/statistics.py, tradeexecutor/statistics/core.py
=> Move long short 2

.github/workflows/test-and-build-image.yml, .github/workflows/test-slow.yml, tests/cli/test_http_log.py, tests/enzyme/test_enzyme_end_to_end.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py, tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/enzyme_deploy_vault.py, tradeexecutor/ethereum/web3config.py
- Update Enzyme vault deployment to use updated Enzyme vault configuration with guard, terms of service and new payment forwarder
=> New enzyme vault deploy

notebooks/rsi/rsi-70-30.ipynb, tests/test_binance_data.py, tradeexecutor/backtest/backtest_generic_router.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/pandas_trader/alternative_market_data.py, tradeexecutor/utils/binance.py, tradeexecutor/visual/utils.py
- Fix Binance data being corrupted in upsampling stop loss candle -> strategy price candle
=> Fix multipair data resamping

notebooks/rsi-momentum/README.md, tradeexecutor/analysis/advanced_metrics.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/cli/log.py, tradeexecutor/state/identifier.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/notebook.py, tradeexecutor/visual/benchmark.py, tradeexecutor/visual/equity_curve.py, tradeexecutor/visual/technical_indicator.py, tradeexecutor/visual/utils.py
- The V2 of RSI momentum example strategy
- More dev experience polish
=> Rsi example 2

tradeexecutor/cli/commands/repair.py
=> add engine version

tradeexecutor/statistics/statistics_table.py
=> correct live return % for performance page

scripts/analyse-1delta-trade.py, tradeexecutor/cli/commands/retry.py, tradeexecutor/cli/main.py, tradeexecutor/ethereum/one_delta/analysis.py, tradeexecutor/ethereum/rebroadcast.py, tradeexecutor/state/retry.py
- Add command to analyze 1delta trade based on tx hash
- Add command to retry (rebroadcast for now) failed trades
=> Debug failed trade and retry

poetry.lock, pyproject.toml, tests/test_binance_data.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/strategy/pandas_trader/alternative_market_data.py, tradeexecutor/utils/binance.py, tradeexecutor/visual/equity_curve.py
- More examples and fixes to RSI momentum notebooks
=> Even more RSI

.github/workflows/test-and-build-image.yml, .github/workflows/test-slow.yml, tradeexecutor/statistics/summary.py, tradeexecutor/visual/equity_curve.py
=> fix resampling

tests/ethereum/polygon_forked/1delta/conftest.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tradeexecutor/ethereum/one_delta/analysis.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/one_delta/one_delta_valuation.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/state/loan.py, tradeexecutor/state/state.py, tradeexecutor/strategy/pandas_trader/position_manager.py
=> 1delta credit supply position

tradeexecutor/backtest/backtest_runner.py, tradeexecutor/strategy/pandas_trader/indicator.py
- Messes up Datalore notebooks
=> Don't show indicator load progress in grid search

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/testtrade.py, tradeexecutor/state/position.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/trading_strategy_universe.py
- Added credit supply test to `perform-test-trade`
- Added a simple notebook for strategy which mixes spot and credit supply positions
=> Test credit supply trade and notebook

tests/mainnet_fork/test_enzyme_guard_perform_test_trade.py, tests/mainnet_fork/test_trading_strategy_engine_v050_live_trading.py, tradeexecutor/cli/commands/check_wallet.py
- Add integration test for guarded Enzyme vault deployment
- Fix issue with the too late block number for Enzyme vault deployment data
=> Guarded perform-test-trade works

strategies/matic-eth-usdc.py, strategies/test_only/test_trading_strategy_engine_v050.py, tradeexecutor/cli/commands/console.py, tradeexecutor/cli/commands/enzyme_deploy_vault.py, tradeexecutor/cli/commands/repair.py, tradeexecutor/cli/commands/retry.py, tradeexecutor/cli/commands/start.py, tradeexecutor/strategy/bootstrap.py, tradeexecutor/strategy/strategy_module.py
- Chahnge to use `Parameters.chain_id` instead of `StrategyModule.chain_id`
=> Chain id fix

tests/interest/test_lending_dataset.py, tests/interest/test_missing_lending_data.py, tests/test_data_age.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/strategy_module.py, tradeexecutor/strategy/universe_model.py
- Fix bad uses of `ExecutionMode` and `UniverseOptions` in the code base
=> Further unit testing fixes

tradeexecutor/analysis/grid_search.py, tradeexecutor/utils/sort.py, tradeexecutor/visual/grid_search.py
- Show only the unique result in the best grid search result table
=> Add unique_only sort fo grid search results

tests/backtest/test_backtest_credit_supply_mock.py, tests/backtest/test_backtest_inline_synthetic_data.py, tradeexecutor/analysis/trade_analyser.py
=> fixes `time_in_market` doesn't include last position if it is closed #859

tests/test_summary_and_metrics.py, tradeexecutor/statistics/key_metric.py, tradeexecutor/strategy/summary.py
- Adding a new key metric for the frontend
=> Adding trades per month metric

tradeexecutor/analysis/trade_analyser.py
Adds long short %'s to frontend
=> Adds long/short %'s to frontend

tradeexecutor/ethereum/one_delta/one_delta_routing.py
=> fixes Incorrect type for trade `executed_collateral_allocation` #771

.github/workflows/test-and-build-image.yml, .github/workflows/test-slow.yml, tests/ethereum/polygon_forked/1delta/conftest.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/strategy/lending_protocol_leverage.py
Fix `portfolio_value_at_open` when we close credit supply position and open another spot position in the same cycle
Fix #864
=> Fix credit supply portfolio value

tradeexecutor/cli/commands/visualise.py, tradeexecutor/cli/main.py, tradeexecutor/state/portfolio.py, tradeexecutor/strategy/pandas_trader/position_manager.py
- Add `visualise` command to test Discord image in trading cycle
- Add `get_closed_position_for_pair()` method to check historical position of a pair
=> Visualise command

tradeexecutor/visual/strategy_state.py
=> make legend transparent

tradeexecutor/state/position.py
- Clean up `get_realised_profit()` code a bit
=> Unrealised pnl cleanup

tradeexecutor/state/position.py, tradeexecutor/state/statistics.py, tradeexecutor/state/types.py, tradeexecutor/statistics/core.py, tradeexecutor/visual/equity_curve.py
- We tracked TVL/net profit before - but this metric is skewed by deposits and redemptinos
- Now track all-time unrealised profitability as well and plan to have it as the main chart
=> Add unrealised_profitability to portfolio stats

tradeexecutor/analysis/trade_analyser.py
=> fix time_in_market bug #891

.github/workflows/devcontainer.yml
- Add a step to build and push Dev Container image as the part of the build process
=> Add dev container

strategies/test_only/test_trading_strategy_engine_v050.py, tests/backtest/test_decide_trades_v4.py, tests/backtest/test_indicator.py, tests/backtest/test_visualise_market_regime_filte.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/visual/bullbear.py
- Create a regime filter visualisation and debug functions
- Create a sample ADX based regime filter using Binance daily data
- 20 days ADX 
- Direction positive (DP) > 25 bull
- Direction negative (DN) > 25 bear
- Otherwise crab
[About ADX here](https://www.investopedia.com/terms/a/adx.asp).
=> Add regime filter visualisation

tests/backtest/test_visualise_market_regime_filte.py, tradeexecutor/analysis/regime.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/utils/binance.py, tradeexecutor/visual/bullbear.py
- `Regime` class is now good to import in the strategies 
- Try to deal with different timeframes for indicators and price series and decision cycle with `get_indicator_value(data_delay_tolerance)`
=> Refactor regime to its own module

tests/backtest/test_visualise_hour_weekday.py, tests/backtest/test_visualise_market_regime_filte.py, tradeexecutor/analysis/timemap.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/binance.py
- Add working hour heatmap
- Add `forward_fill` to `create_binance_universe` to fix the data gaps when Binance was down
- Off by default for now, because toggling it causes too much unrelated havoc with Pandas DataFrame indexes
=> Weekday heatmap

tests/backtest/test_indicator.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/python_function.py
- Avoid using stale indicator cache data leading to confusing results
- Add indicator function body hash as the part of the cache key
- Add forward fill as the parameter of universe cache key
=> Better indicator data caching keys

tradeexecutor/backtest/backtest_runner.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/pandas_trader/strategy_input.py
- Allow use to custom CSV data as a trading signal in a portfolio construction model
=> Alternative data

tests/backtest/test_decide_trades_v4.py
- Make sure indicator cache works with `run_backtest_inline`
=> Indicator cache issue

strategies/eth-breakout-atr-1h-aave.py, tradeexecutor/backtest/backtest_report_template.ipynb, tradeexecutor/strategy/pandas_trader/position_manager.py
- New strategy module
- Bug fixes
=> Add lending positions to ATR strategy

strategies/eth-breakout-atr-1h-aave.py, tests/enzyme/test_enzyme_end_to_end_multipair.py, tests/mainnet_fork/test_enzyme_guard_perform_test_aave.py, tests/mainnet_fork/test_enzyme_guard_perform_test_aave_v3.py, tradeexecutor/cli/commands/enzyme_deploy_vault.py, tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/testtrade.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/state/state.py, tradeexecutor/state/trade.py
- Add `perform-test-trade` support for Aave positions
=> Credit position test trade

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py, tradeexecutor/state/trade.py
- `TradingPosition.notes` was overwritten with an empty string
=> Fix note field erased by stop loss close

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/state/portfolio.py, tradeexecutor/state/position.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/stop_loss.py, tradeexecutor/visual/utils.py
- Display notes on the trade candle chart
=> Notes fix 2

tests/test_equity_curve.py, tests/web/test_webhook_api.py, tradeexecutor/visual/equity_curve.py, tradeexecutor/visual/web_chart.py
- Export sampled profitability % to the web
=> Add WebChartType.compounding_unrealised_trading_profitability_sampled

strategies/test_only/enzyme_e2e_mixed_positions.py, tests/mainnet_fork/test_enzyme_guard_credit_positions.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/hot_wallet_sync_model.py, tradeexecutor/strategy/interest.py
=> Add sync_interests to EnzymeVaultSyncModel

tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/dust.py
- Increase tolerance for aPolUSDC due to Aave accounting issues
=> Work around further Aave issues

tests/web/test_webhook_api.py, tradeexecutor/webhook/api.py
=> Icon url fix

tests/backtest/test_binance.py, tests/test_binance_data.py
=> binance test fix

tests/backtest/test_indicator.py, tradeexecutor/strategy/pandas_trader/indicator.py
Example
```
indicators.add(
"ema",
pandas_ta.ema,
{"length": 10},
IndicatorSource.close_price,
)
indicators.add(
"ema_4h",
pandas_ta.ema,
{"length": 10},
IndicatorSource.close_price,
time_bucket=TimeBucket.h4,
)
```
- fixes #961
=> update trading strategy

poetry.lock, pyproject.toml, tests/backtest/test_decide_trades_v4.py, tests/backtest/test_grid_search.py, tests/backtest/test_indicator.py, tests/backtest/test_optimiser.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/backtest/optimiser.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/execution_context.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/parameters.py
- Add scikit-optimise based optimiser as an alternative for grid search
=> Add Optimiser

tests/backtest/test_grid_search.py, tradeexecutor/analysis/grid_search.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/backtest/optimiser.py
- Add win rate optimiser
- Deal with duplicate grid combinations created by the optimiser
=> More small fixes for optimiser

tests/backtest/test_indicator.py, tradeexecutor/strategy/pandas_trader/indicator.py
=> Fix indicator dependency resolution when use memory storage

tests/backtest/test_optimiser.py, tradeexecutor/analysis/grid_search.py, tradeexecutor/analysis/multi_asset_benchmark.py, tradeexecutor/analysis/optimiser.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/backtest/optimiser.py, tradeexecutor/backtest/optimiser_functions.py, tradeexecutor/visual/grid_search.py
- Move optimiser result functions to a separate module for readability and discoverability
- Shorten grid search result labels
- Make it possible to visualise optimised search value in the grid search result table
=> Split optimiser functions

tests/backtest/test_backtest_inline_synthetic_data.py, tests/backtest/test_backtest_mixed_positions.py, tests/strategy_tests/test_defi_bluechip.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/strategy/trading_strategy_universe.py
- Fixes bugs in `time_in_market` and `time_in_market_volate` calculation.
- Possible that it is not 100% correct, but future bugs will be much easier to fix
- Fixes #978 by fixing the calculation value our side. The very low values from quantstats can be assumed to be incorrect
- No current test values were changed, only additions made
=> Time in market fix

tradeexecutor/backtest/backtest_report_template.ipynb
add state and time_bucket to `calculate_summary_statistics`
=> fix backtest report template

tests/backtest/test_grid_search.py, tradeexecutor/backtest/grid_search.py
- The first attempt did not work as intended
=> Fix nesting of OutOfSimulatedWalletBalance exception

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/bootstrap.py, tradeexecutor/strategy/factory.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/runner.py
- With `VISULALISATION=false` disable further drawing code
- Trying to workaround Alchemy.com crap
=> More visualisation flags

tests/strategy_tests/test_increase_credit.py, tradeexecutor/backtest/backtest_runner.py, tradeexecutor/strategy/pandas_trader/position_manager.py
- Add a high level backtest to gradually increase credit supply position size
- Add method `PositionManager.add_cash_to_credit_supply()`
=> Increase credit

tradeexecutor/cli/bootstrap.py, tradeexecutor/ethereum/enzyme/vault.py
- Was using hardcoded Polygon address
=> Fund value calculator wrong for Ethereum

tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/strategy/account_correction.py
- CLI `correct-accounts` struggled with gained interest
=> Add code to sync missing credit

.github/workflows/test-and-build-image.yml, poetry.lock, pyproject.toml, tests/enzyme/test_enzyme_end_to_end.py, tests/web/test_webhook_main_loop_crash.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/cycle.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/parameters.py
- Dump strategy parameters on startup
- Add `--run-single-cycle` to test the strategy cycle and force the strategy cycle execution
=> Test decision cycle

tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py
- Universe may not available if it is trigger based
=> Fix the universe construction for --run-single-cycle

tradeexecutor/cli/loop.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/trading_strategy_universe.py
- Do not start scheduler when doing a single shot
- Add more diagnostics to `load_partial_data()`
=> Single shot no scheduler

tradeexecutor/backtest/backtest_module.py, tradeexecutor/cli/commands/console.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/pandas_trader/strategy_input.py
- Allows you to debug indicator data from `console` subcommand
=> Expose indicators in the strategy console

tradeexecutor/analysis/optimiser.py
- Do not display results that did not pass `result_filter` by default
=> Optimiser result filter

tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py
=> Fix adjusting credit position with 1delta

tradeexecutor/state/position.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/strategy_input.py
- Add `update_stop_loss(trailing)` and document its usage
=> Make it easier to support custom trailing stop losses

strategies/test_only/enzyme-polygon-eth-rolling-ratio.py, tests/mainnet_fork/test_repair_frozen_credit_position.py, tradeexecutor/cli/commands/repair.py, tradeexecutor/state/position.py, tradeexecutor/state/repair.py, tradeexecutor/strategy/asset.py
Fix #1023 
Handle repair for credit supply positions.
=> Support repairing frozen credit position

tradeexecutor/state/position.py
=> Fix realized profit calculation on credit position

tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py
=> Support simulate single cycle

strategies/test_only/enzyme_e2e_credit.py, tests/mainnet_fork/test_enzyme_credit_position.py
Part of https://github.com/tradingstrategy-ai/strategies/issues/14
=> Add forked credit position tests

strategies/test_only/enzyme_e2e_credit.py, tests/backtest/test_grid_search.py, tests/mainnet_fork/test_enzyme_credit_position.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/strategy/lending_protocol_leverage.py
=> Update credit supply loan when there is redemption

tests/backtest/test_grid_search.py, tests/ethereum/polygon_forked/conftest.py, tests/ethereum/polygon_forked/generic-router/conftest.py, tests/mainnet_fork/test_uniswap_v2_polygon.py, tradeexecutor/analysis/slippage.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pricing_model.py, tradeexecutor/utils/slippage.py
Validate and convert slippage from percent to bps in 1 place
Fix #1043
=> Fix wrong slippage conversion

tests/backtest/test_backtest_partial_take_profit.py, tradeexecutor/state/position.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/stop_loss.py
Close #1046 
NOTE: there will be another PR to finalize the support for market limit positions as well
=> Improve partial take profit

tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/runner.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/strategy/weighting.py
- Add safety asserts
- Allow empty normalised weights
=> Fixing issues with alpha model and new TVL size risk model

tradeexecutor/strategy/pandas_trader/decision_trigger.py
=> Force wait for universe data to use 1h lending candles as well

tradeexecutor/ethereum/aave_v3/aave_v3_routing.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/routing_state.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_routing.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py
Create default gas limit for each action (approve, swap) per chain
=> Replace hardcoded gas limits with default per chain

tests/backtest/test_other_data.py, tradeexecutor/state/other_data.py, tradeexecutor/state/state.py
- Add `State.other_data` where strategies can store custom variables in `decide_trades`
=> Add other_data

tradeexecutor/ethereum/routing_state.py
Temp solution to override default gas limits using envvar
=> Support override default gas limit using envvar

poetry.lock, pyproject.toml, tests/cli/test_telegram_logging.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/log.py
- Add Telegram trade output
- See pending PR in the dependency: https://github.com/arynyklas/telegram_bot_logger/pull/1
=> Telegram logger

tradeexecutor/cli/log.py, tradeexecutor/ethereum/web3config.py, tradeexecutor/strategy/runner.py
- Add new `logging.TRADE_HIGH` level designated for Telegram logging output
=> Trade high logging level

tests/mainnet_fork/test_strategy_fetch_tvl.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/log.py, tradeexecutor/ethereum/tvl.py, tradeexecutor/ethereum/web3config.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/strategy/parameters.py, tradeexecutor/strategy/runner.py
- Add `fetch_quote_token_tvls()` helper method for real-time TVL fetch, with an example how to dynamically size your trades based on the available Uniswap v2 or v3 lit liquidity
- Expose `StrategyInput.web3` instance for live trading strategies for real-time onchain data decision making
=> Real time TVL measurement and position sizing

.github/workflows/docker.yml, .github/workflows/test-and-build-image.yml, .github/workflows/test-slow.yml, tests/conftest.py, tests/test_strategy_state_visualisation_multipair.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/strategy/tvl_size_risk.py, tradeexecutor/visual/asset_correlation.py
- Add autoheal for OHLCV data
- Update dataset cache paths for CI
- Add asset correlation matrix
- Handle missing TVL values when doing position sizing
=> Index strategy updates

tests/backtest/test_backtest_visualise_weights.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tradeexecutor/analysis/weights.py, tradeexecutor/state/other_data.py, tradeexecutor/state/statistics.py, tradeexecutor/statistics/core.py, tradeexecutor/strategy/trading_strategy_universe.py
- Extract asset weighting from the portfolio statistics stored in the state
- Add `tradeexecutor.visual.weights` to plot different charts of portfolio asset weightings over time
=> Asset weight chart

tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/mainnet_fork/test_trading_strategy_engine_v050_live_trading.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/state/validator.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/timestamp.py
- Make several error and assert messages more helpful
- Avoid passing too heavy TokenSniffer data around
=> Minor fixes to error messages and data passing

tests/cli/test_cli_check_universe.py, tests/cli/test_cli_commands.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tests/mainnet_fork/test_price_impact_crash.py, tradeexecutor/cli/commands/backtest.py, tradeexecutor/cli/commands/check_universe.py, tradeexecutor/strategy/bootstrap.py, tradeexecutor/strategy/engine_version.py, tradeexecutor/strategy/execution_context.py
- Fix check-universe CLI command
=> Check strategy Parameters class in check-universe

tests/units_tests/test_parse_pair_data.py, tradeexecutor/cli/commands/check_universe.py, tradeexecutor/cli/commands/pair_mapping.py, tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/testtrade.py
- Because you need to pass pair id to `perform-test-trade` command
=> check-universe command display available trading pairs

tradeexecutor/cli/commands/perform_test_trade.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/slippage.py
- Clean up slippage tolerance config to its own module
=> Max slippage config

tests/cli/test_cli_commands.py, tradeexecutor/cli/commands/send_log_message.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/main.py
- Add `send-log-message` command to test loggers
=> Cli send log message

tests/ethereum/test_uniswap_v3_live_pricing.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/ethereum/tvl.py
- Implement `get_quote_token_tvl()` and `get_usd_tvl()` in `EthereumPricingModel` so that strategies can use real-time TVL data
=> Real time TVL fetch

tests/ethereum/test_tvl_routing_mixed.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/strategy/generic/generic_router.py, tradeexecutor/strategy/runner.py
- Make sure we can get TVL for all pairs if we mix Uniswap v2/v3 pairs in `PricingModel`
=> Fix TVL routing in mixed universe

tests/ethereum/test_tvl_routing_mixed.py, tradeexecutor/ethereum/eth_pricing_model.py, tradeexecutor/ethereum/ethereum_protocol_adapters.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py
=> Buy price routing issue

tradeexecutor/strategy/pandas_trader/position_manager.py
- Fix adjust_position() to handle slippage tolerance directionally
=> Include token tax in adjust_position()

tradeexecutor/ethereum/routing_model.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/utils/slippage.py
=> Include tax in adjust positio 2

tests/mainnet_fork/test_uniswap_v3_routing.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py, tradeexecutor/strategy/output.py
- MEV Blocker must broadcast and confirm each tx sequentially
=> MEV Blocker compatible broadcast

tradeexecutor/analysis/position.py, tradeexecutor/cli/commands/console.py, tradeexecutor/cli/commands/repair.py, tradeexecutor/ethereum/eth_valuation.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_valuation_v0.py, tradeexecutor/state/repair.py, tradeexecutor/state/valuation.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/valuation.py
- Deal with zero quantity positions
=> Quantity debug

strategies/test_only/ethereum-memecoin-vol-basket.py, tests/cli/test_cli_check_universe.py, tests/cli/test_console.py, tradeexecutor/cli/commands/console.py, tradeexecutor/strategy/pandas_trader/indicator.py
- vol-basket strategy refused to open console
=> Fix console command does not start with indicators

tradeexecutor/cli/commands/webapi.py, tradeexecutor/statistics/key_metric.py
Part of https://github.com/tradingstrategy-ai/strategies/issues/20
=> Temp fix inf value

tests/cli/test_console.py, tests/legacy/test_repair_zero_quantity_position.py, tests/mainnet_fork/test_enzyme_credit_position.py, tradeexecutor/ethereum/execution.py
=> Keep execution going even if there is frozen positions

strategies/test_only/defi-bluechip-momentum.py, tests/strategy_tests/test_defi_bluechip.py, tradeexecutor/state/size_risk.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/utils/dedent.py
- Add human readable diagnostics data to alpha model
- Record and make loggable more info on why positions where decided as they were
=> Alpha model diagnostics

strategies/test_only/defi-bluechip-momentum.py, strategies/test_only/memecoin_index.py, strategies/test_only/test_trading_strategy_engine_v050.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py, tests/mainnet_fork/test_memecoin_index.py, tradeexecutor/cli/commands/start.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/trading_strategy_universe.py
- More information on why or why not a rebalance was triggered
=> Add more alpha model dianogstics vars and functions

tests/mainnet_fork/conftest.py, tests/mainnet_fork/test_uniswap_v3_routing.py, tradeexecutor/cli/close_all.py, tradeexecutor/cli/commands/close_all.py
- Was missing
- Further MEVBlocker bad behaviour workarounds
=> Add slippage tolerance to close all

strategies/test_only/memecoin_index.py, tests/mainnet_fork/test_memecoin_index.py, tradeexecutor/cli/commands/start.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/routing_state.py, tradeexecutor/ethereum/tx.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/asset.py, tradeexecutor/strategy/pandas_trader/runner.py
- Reduce massive per-pair output for multipair strategy, breaking Discord logging
- Correctly output custom strategy thinking messages for multipair strategies 
- Add token tax filter to get rid of unwanted trading pairs
- Fix transaction broadcast issues and logging in many places
=> Sanitise strategy thinking output for multipair strategy

tradeexecutor/strategy/output.py, tradeexecutor/strategy/runner.py
- Currently too messy, optimised for Discord output
=> Make Telegram strategy report more readable

tests/velvet/conftest.py, tests/velvet/test_velvet_deposit.py, tests/velvet/test_velvet_swap.py, tests/velvet/test_velvet_sync_positions.py, tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/ethereum/balance_update.py, tradeexecutor/ethereum/ethereum_protocol_adapters.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_live_pricing.py, tradeexecutor/ethereum/velvet/vault.py, tradeexecutor/state/balance_update.py, tradeexecutor/strategy/dust.py, tradeexecutor/strategy/execution_model.py, tradeexecutor/strategy/routing.py, tradeexecutor/strategy/trading_strategy_universe.py
- Check that we manage to sync Velvet deposits and redemptions
- Add skeleton for Velvet swap and intent-based routing
=> Velvet deposit test runs

.github/workflows/test.yml, tests/ethereum/polygon_forked/generic-router/conftest.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/velvet/conftest.py, tests/velvet/test_velvet_swap.py, tests/velvet/test_velvet_sync_positions.py, tradeexecutor/backtest/backtest_execution.py, tradeexecutor/backtest/backtest_routing.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/routing_model.py, tradeexecutor/ethereum/tx.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_execution_v0.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_live_pricing.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py, tradeexecutor/ethereum/velvet/execution.py, tradeexecutor/ethereum/velvet/tx.py, tradeexecutor/ethereum/velvet/velvet_enso_routing.py, tradeexecutor/state/position.py, tradeexecutor/state/state.py, tradeexecutor/strategy/dust.py, tradeexecutor/strategy/generic/generic_pricing_model.py, tradeexecutor/strategy/generic/generic_router.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/routing.py
- Try to get Enso to function
- Velvet and Enso shit is f*king broken untestable mess, but going to merge this any case
=> More Velvet swap work

.github/workflows/test.yml, pyproject.toml, strategies/test_only/base-memecoin-index.py, strategies/test_only/ethereum-memecoin-vol-basket.py, tests/backtest/test_indicator_decorator.py, tests/cli/test_http_log.py, tests/cli/test_telegram_logging.py, tests/ethereum/test_tvl_routing_mixed.py, tests/legacy/test_repair_zero_quantity_position.py, tests/test_ring_buffer_logging_handler.py, tests/test_strategy_cycle_trigger.py, tests/test_strategy_state_visualisation.py, tests/velvet/test_velvet_sync_positions.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/pandas_trader/indicator_decorator.py
- Define notebook indicators using Python decorators, making the code much more readable and shorter
- Cleaning up tests, as Github worker is crashing for some reason
- For some reason, automated tests (not slow group) fail on Github CI to some kind of internal Github timeout. They still work locally.
=> Indicator decorator

strategies/eth-btc-usdc-size-risk.py, strategies/test_only/base-memecoin-index.py, strategies/test_only/ethereum-memecoin-vol-basket.py, strategies/test_only/memecoin_index.py, tests/backtest/test_backtest_inline_synthetic_data.py, tradeexecutor/analysis/advanced_metrics.py, tradeexecutor/analysis/multi_asset_benchmark.py, tradeexecutor/cli/commands/backtest.py, tradeexecutor/cli/commands/start.py, tradeexecutor/state/size_risk.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/strategy/tvl_size_risk.py
- Misc. alpha model diagnostics improvements
- Small typo and comment fixes
=> More alpha model debug

tradeexecutor/cli/commands/perform_test_trade.py
- Add `perform-test-trade --amount`
=> Allow different test amounts on the cmd line

tradeexecutor/cli/commands/check_universe.py, tradeexecutor/strategy/bootstrap.py
- Have manual test coverage before `trade-executor start`
=> Check create_indicators() in check-universe CLI command

tests/mainnet_fork/test_strategy_fetch_tvl_base.py, tradeexecutor/cli/close_all.py, tradeexecutor/cli/commands/check_universe.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/velvet/execution.py, tradeexecutor/strategy/runner.py
- Velvet needs it special `sync_positions()` code
- Handle it in the loop
=> Sync Velvet positions in loop

tests/interest/test_state_credit_supply.py, tests/interest/test_state_short.py, tests/velvet/test_velvet_swap.py, tradeexecutor/cli/commands/deploy_guard.py, tradeexecutor/ethereum/aave_v3/aave_v3_routing.py, tradeexecutor/ethereum/one_delta/one_delta_routing.py, tradeexecutor/ethereum/velvet/velvet_enso_routing.py
- Let's see if Velvet/Enso can handle sequential buys of different tokens
=> Velvet fixes for managing multiple token buys through Enso

tradeexecutor/cli/bootstrap.py, tradeexecutor/cli/commands/start.py, tradeexecutor/state/metadata.py, tradeexecutor/strategy/execution_model.py
- Expose Velvet metadata like smart contract addresses to the frontend
=> Velvet metadata

.github/workflows/test-slow.yml, .github/workflows/test.yml, tests/cli/test_telegram_logging.py, tests/enzyme/conftest.py, tests/lagoon/conftest.py, tests/lagoon/test_lagoon_deposit.py, tests/lagoon/test_lagoon_e2e.py, tests/lagoon/test_lagoon_swap.py, tests/velvet/test_velvet_sync_positions.py, tradeexecutor/cli/commands/backtest.py, tradeexecutor/cli/commands/lagoon_deploy_vault.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/show_positions.py, tradeexecutor/ethereum/address_sync_model.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/ethereum/lagoon/execution.py, tradeexecutor/ethereum/lagoon/tx.py, tradeexecutor/ethereum/lagoon/vault.py, tradeexecutor/ethereum/swap.py, tradeexecutor/state/balance_update.py, tradeexecutor/state/blockhain_transaction.py, tradeexecutor/state/sync.py, tradeexecutor/strategy/strategy_module.py, tradeexecutor/strategy/sync_model.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/slippage.py
- Complete `LagoonSyncModel` to handle ERC-7540 syncs
=> Lagoon deposit and redemptions

tradeexecutor/strategy/tag.py
=> Add "archived" strategy tag

strategies/base-memex.py, tests/lagoon/conftest.py, tradeexecutor/analysis/multi_asset_benchmark.py, tradeexecutor/analysis/weights.py, tradeexecutor/backtest/backtest_report_template.ipynb, tradeexecutor/cli/commands/backtest.py, tradeexecutor/cli/result.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/visual/equity_curve.py
- Small usability improvements
- Clean backtest report for warnings
- Add `decide_trades()` messages to the backtesting report template
- Add asset weight allocation to the backtesting report  template
=> Ergonomy fixes to backtest command

strategies/base-memex.py, tests/backtest/test_backtest_inline_real_data.py, tests/lagoon/test_lagoon_swap.py, tests/mainnet_fork/test_frozen_position_and_blacklist.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/runner.py
- Add `PositionManager.get_pending_redemptions()`
- Improve Telegram reporting
=> Add Lagoon redemption queue support to PositionManager

strategies/test_only/base-memecoin-index.py, tests/mainnet_fork/test_enzyme_credit_position.py, tradeexecutor/analysis/pair.py, tradeexecutor/cli/loop.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/trading_strategy_universe.py
- Add rugpull black list
- Show tradeable universe at the startup
=> Velvet strategy enhanchement

strategies/base-memex.py, strategies/test_only/base-memecoin-index.py, tests/enzyme/test_enzyme_uniswap_v3_polygon_fork.py, tests/lagoon/test_lagoon_e2e.py, tests/mainnet_fork/test_velvet_e2e.py, tradeexecutor/analysis/credit.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/uniswap_v3/uniswap_v3_routing.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/alpha_model.py, tradeexecutor/visual/grid_search_visualisation.py
- Debug Base trading issues, by adding even more logging
- Add `generate_rebalance_trades_and_triggers(sell_rebalance_min_threshold)` so we can generate small enough sell trades for micro portfolios
=> More Base trade debug

tests/cli/test_cli_commands.py, tests/cli/test_cli_show_positions_long.py, tradeexecutor/analysis/position.py, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/show_positions.py, tradeexecutor/cli/commands/show_valuation.py, tradeexecutor/cli/main.py
- Add CLI `show-valuation` command for manual comparison of position valuations
-> Helps to find out causes in disparencies in trade execution and value
=> CLI valuation output

poetry.lock, pyproject.toml, tests/backtest/test_backtest_credit_flow.py, tests/mainnet_fork/test_enzyme_credit_position.py, tradeexecutor/analysis/pair.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/backtest/optimiser.py, tradeexecutor/cli/commands/start.py, tradeexecutor/strategy/alpha_model.py
- Add frozen position check inside `generate_rebalance_trades_and_triggers` so we do not try to trade on a frozen position (increase/decrease)
-
=> Alpha model frozen position check

tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/cli/commands/show_valuation.py, tradeexecutor/cli/double_position.py
- Do not allow to proceed to correct-accounts if we have multiple positions open for a same token
=> Add double position check

tests/enzyme/test_enzyme_redeem.py, tests/legacy/test_repair_trade_missing_tx.py, tradeexecutor/state/position.py
Part of https://github.com/tradingstrategy-ai/strategies/issues/28
=> Fix position value calculation on Velvet

strategies/test_only/base-ath.py, tests/mainnet_fork/test_lagoon_guard_perform_test_aave_v3.py, tradeexecutor/cli/commands/lagoon_deploy_vault.py, tradeexecutor/ethereum/ethereum_protocol_adapters.py
- Allow Aave v3 aUSDC deposits and withdrawals from a Lagoon vault using out Zodiac guard
=> Enable Aave guard on Lagoon vault

tradeexecutor/cli/loop.py, tradeexecutor/state/interest.py, tradeexecutor/strategy/interest.py, tradeexecutor/strategy/sync_model.py, tradeexecutor/utils/accuracy.py
- Lagoon vaults did not have good interest data when updating valuations
=> Add update_position_valuations(interest=True) as the default behaviour

tradeexecutor/analysis/trade_analyser.py, tradeexecutor/analysis/weights.py, tradeexecutor/state/position.py, tradeexecutor/state/statistics.py, tradeexecutor/statistics/core.py, tradeexecutor/visual/equity_curve.py
- Make sure accrued interest if reflected in the strategy profitability %
=> Include credit % in unrealised profitability

tests/backtest/test_min_tvl_universe.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/mainnet_fork/aave_v3/test_aave_v3_live_credit_supply.py, tests/mainnet_fork/test_credit_position_profitability.py, tradeexecutor/backtest/simulated_wallet.py, tradeexecutor/cli/loop.py, tradeexecutor/ethereum/enzyme/vault.py, tradeexecutor/strategy/interest.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/utils/accuracy.py
- Add `load_partial_data(preloaded_tvl_df)`
- Fix test time warp/interest rate issues caused by change of underlying Anvil
=> load_partial_data() preloaded_tvl_df support

strategies/test_only/base-ath.py, tests/mainnet_fork/test_correct_accouting_closed_position_has_ausdc.py, tests/mainnet_fork/test_correct_accouting_position_should_be_open.py, tests/mainnet_fork/test_correct_credit_position_redemption.py, tests/mainnet_fork/test_correct_interest_not_accrued.py, tests/mainnet_fork/test_repair_credit_position_open_failed.py, tests/mainnet_fork/test_repair_frozen_credit_position.py, tradeexecutor/state/position.py, tradeexecutor/state/repair.py, tradeexecutor/strategy/lending_protocol_leverage.py
- Fix lingering Aave position where supply has failed and position has nominal zero value
=> Repair credit position open failed

tests/mainnet_fork/test_repair_credit_position_open_failed.py, tradeexecutor/state/interest.py, tradeexecutor/state/state.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/output.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/runner.py, tradeexecutor/utils/accuracy.py
- Watch out for the situations with double credit positions
=> Adding more double credit position diagnostics

tests/backtest/test_forward_fill.py, tests/mainnet_fork/test_velvet_e2e.py, tests/test_strategy_cycle_trigger.py, tests/velvet/test_velvet_swap.py, tradeexecutor/analysis/curve.py, tradeexecutor/analysis/multi_asset_benchmark.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/utils/notebook.py
- Cannot use `hash()` with filename slugs in Python
=> Make sure indicator cache files have deterministic names

tests/ethereum/polygon_forked/1delta/test_one_delta_live_credit_supply.py, tradeexecutor/backtest/backtest_module.py, tradeexecutor/ethereum/routing_data.py, tradeexecutor/ethereum/velvet/velvet_enso_routing.py
=> Upgrade Velvet swap API

strategies/test_only/velvet-position-enter-check.py, tests/velvet/test_velvet_check_enter_position.py, tradeexecutor/ethereum/velvet/velvet_enso_routing.py, tradeexecutor/state/visualisation.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/pandas_trader/strategy_input.py, tradeexecutor/strategy/qstrader/runner.py, tradeexecutor/strategy/routing.py, tradeexecutor/strategy/runner.py
- Looks like Enso cannot route us certain BNB Smart Chain pairs even if they are there
- As a workaround, the strategy logic need to double check the trading pair availability on Enso router
=> Velvet and Enso tradebility check

.github/workflows/docker.yml, poetry.lock, pyproject.toml, tradeexecutor/cli/commands/shared_options.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/log.py
=> Integrate Sentry 

.github/workflows/test.yml, pyproject.toml, tests/backtest/test_backtest_ema_crossover.py, tests/backtest/test_backtest_inline_real_data.py, tests/mainnet_fork/test_correct_credit_position_redemption.py, tests/test_ring_buffer_logging_handler.py, tradeexecutor/cli/commands/correct_accounts.py, tradeexecutor/ethereum/velvet/velvet_enso_routing.py, tradeexecutor/state/interest_distribution.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/interest.py, tradeexecutor/strategy/lending_protocol_leverage.py
- CLI test for correct-accounts did not correctly pass `--skip-save` option when passed as `SKIP_SAVE=false` environment variables, `skip_save` was always set to `True` regardless of the value of the environment variable
- Looks like there is changed behavior/bug regarding Typer environment variables 
- To get the correct parsing behavior `skip_save` option has not `is_flag=False` set:
```python
skip_save: bool = Option(False, "--skip-save", is_flag=False, envvar="SKIP_SAVE", help="Do not update state file after the account correction. Only used in testing."),
```
=> Testing --skip-save fix

.github/workflows/test-slow.yml, .github/workflows/test.yml, strategies/test_only/crash.py, tests/cli/test_cli_blacklist.py, tests/web/test_webhook_main_loop_crash.py, tradeexecutor/cli/blacklist.py, tradeexecutor/cli/commands/blacklist.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/main.py, tradeexecutor/state/state.py, tradeexecutor/strategy/trading_strategy_universe.py
- Show, add and remove per-strategy blacklisted tokens from command line
- Fix test hang and race condition issues caused by some recent package updates
=> Add CLI blacklist command

tradeexecutor/cli/log.py
=> Improve Sentry logging

tests/backtest/test_forward_fill.py, tests/mainnet_fork/test_check_accounts_low_value_position.py, tradeexecutor/cli/commands/console.py, tradeexecutor/ethereum/lagoon/share_price_retrofit.py, tradeexecutor/state/store.py
- Add share price data when missing
- Needs QuikNode special RPC support
=> Backtest filling of share prices

tests/enzyme/test_enzyme_redeem.py, tests/strategy_tests/test_vault_yield_manager.py, tradeexecutor/visual/position.py
- Try to figure out a fair method of calculating PnL for an open position
=> More PnL calculation options

tests/enzyme/test_enzyme_uniswap_v3_polygon_fork.py, tests/erc_4626/conftest.py, tests/erc_4626/test_vault_pricing.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_live_loop.py, tests/velvet/test_velvet_sync_positions.py, tradeexecutor/ethereum/vault/vault_live_pricing.py, tradeexecutor/statistics/in_memory_statistics.py, tradeexecutor/strategy/pandas_trader/runner.py, tradeexecutor/strategy/pricing_model.py, tradeexecutor/strategy/trade_pricing.py, tradeexecutor/strategy/trading_strategy_universe.py, tradeexecutor/visual/image_output.py
- Fix pricing reverse issue
- Add `VaultPricing.get_usd_tvl()`
- Fix Kaleido 1.0 relaunching Chrome on every call, see https://github.com/plotly/Kaleido/pull/347 - as this was greatly slowing down the test suite
=> Add missing vault pricing functions

strategies/test_only/base-ath-ipor.py, tests/erc_4626/test_vault_pricing.py, tests/lagoon/test_lagoon_e2e.py, tests/mainnet_fork/test_repair_vault_deposit.py, tradeexecutor/ethereum/vault/vault_live_pricing.py, tradeexecutor/state/repair.py, tradeexecutor/strategy/account_correction.py, tradeexecutor/strategy/dust.py, tradeexecutor/strategy/pandas_trader/position_manager.py
- Allow repair vault positions when open deposit tx has failed
- More gracefully handle frozen vault positions
=> Repair position for failed vault open trades

strategies/test_only/base-ath-ipor-aave-bug.py, strategies/test_only/base-ath-ipor.py, tests/mainnet_fork/test_rebalance_vault_yield.py, tests/strategy_tests/test_defi_bluechip.py, tests/strategy_tests/test_defi_bluechip_trailing_stop_loss.py, tradeexecutor/cli/commands/start.py, tradeexecutor/cli/result.py, tradeexecutor/ethereum/execution.py, tradeexecutor/ethereum/uniswap_v2/uniswap_v2_live_pricing.py, tradeexecutor/strategy/interest.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/yield_manager.py, tradeexecutor/utils/notebook.py
- When opening vault positions, Aave withdraws are not being generated
=> Yield management: Aave position does not sell

tests/cli/test_close_position.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tradeexecutor/cli/commands/close_position.py, tradeexecutor/ethereum/vault/vault_routing.py
- The previous default behavior is to add on the blacklist
=> Do not automatically blacklist pairs if we need to clean up some positions with CLI

tests/lagoon/test_lagoon_e2e.py, tests/mainnet_fork/test_broken_profit_data.py, tradeexecutor/statistics/summary.py, tradeexecutor/strategy/summary.py, tradeexecutor/visual/equity_curve.py, tradeexecutor/visual/web_chart.py
- For some reason, the chart is inverted in production
- Added more debug, but probably did not fix the underlying issue yet
=> Add more diagnostics to share price calculations

tests/mainnet_fork/test_broken_profit_data.py, tests/test_summary_and_metrics.py, tradeexecutor/statistics/key_metric.py, tradeexecutor/strategy/summary.py, tradeexecutor/visual/equity_curve.py
- This gives more accurate metrics that match other websites reporting same data
=> Calculate key metrics for Lagoon vaults using Lagoon share price

tests/enzyme/test_enzyme_trade.py, tests/ethereum/polygon_forked/1delta/test_one_delta_live_short.py, tradeexecutor/backtest/preprocessed_backtest.py, tradeexecutor/backtest/preprocessed_backtest_exporter.py, tradeexecutor/strategy/pandas_trader/indicator.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/pandas_trader/yield_manager.py
- DataFrame inner join with TVL and price made trading pairs to have different timeframes
- Fix issues with yield manager rebalance calculations
=> Fix TVL forward fill and resampling when doing prepared datasets

tests/enzyme/test_enzyme_vault_arbitrum_fork.py, tradeexecutor/ethereum/vault/vault_routing.py
=> Vault routing state vs. global state was mixed in vault transaction crafting

.github/workflows/test.yml, tests/web/test_webhook_render_chart.py, tradeexecutor/state/identifier.py, tradeexecutor/strategy/chart/definition.py, tradeexecutor/webhook/api.py
- Check workflow action and toolchain versions
- Add `/chart-registry/pairs` endpoint
=> Update Poetry, Foundry and workflow

tradeexecutor/analysis/pair.py, tradeexecutor/ethereum/execution.py, tradeexecutor/state/identifier.py, tradeexecutor/state/state.py, tradeexecutor/strategy/trading_strategy_universe.py
- Manage Token Risk data in `TradingPairIdentifier`
=> Initial support for Token Risk API

.github/workflows/test-slow.yml, poetry.lock, pyproject.toml, tests/mainnet_fork/test_correct_credit_position_redemption.py, tests/mainnet_fork/test_repair_credit_position_open_failed.py, tradeexecutor/analysis/trade_analyser.py, tradeexecutor/backtest/backtest_pricing.py, tradeexecutor/cli/close_position.py, tradeexecutor/cli/commands/check_universe.py, tradeexecutor/cli/commands/close_position.py, tradeexecutor/cli/commands/lagoon_deploy_vault.py, tradeexecutor/ethereum/execution.py, tradeexecutor/state/trade.py, tradeexecutor/strategy/pandas_trader/position_manager.py, tradeexecutor/strategy/trade_pricing.py
- Adjust pair fee based on the token tax in backtesting
- Fix eth_defi dependencies
- Fix `close-position` `create_trading_universe()` to have the new arguments
- Add separate token tax field to `TradePricing`
=> Include token tax in the backtest

tests/enzyme/test_enzyme_trade.py, tests/ethereum/polygon_forked/generic-router/test_generic_router_end_to_end.py, tradeexecutor/backtest/backtest_pricing.py, tradeexecutor/backtest/grid_search.py, tradeexecutor/ethereum/swap.py, tradeexecutor/state/trade.py
=> Add support for swapExactTokensForTokensSupportingFeeOnTransferTokens

tradeexecutor/strategy/chart/standard/trading_metrics.py, tradeexecutor/strategy/pnl.py
- Handle failed/repair trades in calculate_pnl
- Ensure trading_metrics returns a DataFrame
=> More chart debugging (#3)

tests/test_rebalance.py, tradeexecutor/strategy/alpha_model.py
=> Fix old weight calculation logic

.github/workflows/docker.yml
- See tradingstrategy-ai/getting-started#28
=> Trigger getting-started tests on successful release build

tests/lagoon/test_lagoon_e2e.py, tradeexecutor/cli/commands/lagoon_settle.py, tradeexecutor/cli/main.py, tradeexecutor/cli/settle_vault.py
- Manually allows to update NAV and settle deposit/redemptions
=> Add lagoon-settle CLI command
